### ISSUE TITLE
Frame debug names are jibberish (again?)

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1012]
I thought we found and fixed the frame name debugging sometimes being on the fritz, but apparently not:

![image](https://user-images.githubusercontent.com/173595/89284461-7fa15600-d657-11ea-981d-66ed80c5e9c1.png)

It probably doesn't matter, but just in case ... this example is from PR #998 run with:

```console
$ make tests/bug-723.pdf SILEFLAGS='-d frames'
```

**Comment by alerque** [comment]
This seems like a intermittent / non-determinant / fruitcake issue. It works fine for me right now.

**Comment by alerque** [comment]
I can't replicate this. I think it still exists, but I can't prove it. I did find several issues with frame debugging while hunting it that #1019 will cover, but I'm going to close this until such a time as it actually surfaces again and I can replicate it.

**Comment by ctrlcctrlv** [comment]
Sorry @alerque I have bad news for you. This issue still exists on master. Built under 94a226716c229d7a87be5a275e1cf124fdd4693b.

![image](https://user-images.githubusercontent.com/838783/90303059-a2a1e600-de5f-11ea-8eb5-e0ae6b6f7ec3.png)

```
$ sile -d frames examples.sil
```

I'm sorry I was just about to log off and get some much needed sleep, but I did want to tell you because there's no way I'll remember tomorrow.

The file is `examples.sil` in my [sile-logos](https://github.com/ctrlcctrlv/sile-logos) repository.
