### ISSUE TITLE
When called with PDF, search for `.sil` file in same directory with same name and compile that instead

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1025]
This is an idea for a convenience feature; if you think it's stupid simply close it. :)

**Comment by simoncozens** [comment]
We've been taking this kind of cleverness out, not adding more in. :-) SILE's input is either .sil or some kind of XML file, so just assuming .sil is not necessarily what you want. I miss the convenience of doing the TeX thing and leaving the extension off, but I am slowly learning that Too Much Magic gets you into trouble...

**Comment by alerque** [comment]
In the vast majority of the Unix world commands take input file names and *sometimes* guess their output filename. Sometimes even the output file name needs to be specified. Only in the case of build systems (like GNU Make or Grunt or Meson or whatever) is it appropriate to take an expected output name and infer inputs. SILE has no reliable mechanism for inferring inputs. Given a set of files:

```
mwe.lua
mwe.sil
mwe.xml
```

SILE would have no way of knowing which file to start with. Does the XML include the SIL file for macros or the SIL file include the XML for some content blob or what? Maybe they are unrelated. We simply don't have SILE setup as a build tool, nor should we. There are simply too many permutations that going into build systems that SILE doesn't need to be bothered with.

Since there are many possible failure cases for such a "guessing" mode and no way to be sure we arrived at the right answer, doing what every other tool does and asking you to specify the inputs is not unreasonable.

**Comment by ctrlcctrlv** [comment]
Perhaps I should just use a `Makefile` :o)

**Comment by alerque** [comment]
Yes, `make` is an appropriate tool for that. Or if you want to get crazy, use CaSILE. It might be too opinionated / optimized for books rather than what you do. I don't use it for a lot of article type projects either, custom Makefiles with project-tailored targets are pretty simple in most cases.

Note if you do use `make` you cane have SILE generate dependency lists for you automatically so you don't have to track what files go into a build. See the `-m` flag.
