### ISSUE TITLE
SU.contentToString and \tocentry

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1029]
This issue arises out of end of discussion in #1026, where @alerque helped me find code causing my problem.

Consider e.g.

```tex
\chapter{Dynasties in \em{MacBeth}}
```

For PDF bookmark (table of content entry) purposes, SILE interprets it as `Dynasties in `.

This is ultimately because in `pdf.lua` `SILE.Commands.tocentry` calls `SU.contentToString` to get the title, which, per its doc-comment, "[f]latten[s] content trees into just the string components".

I want to PR a new function which would recursively pull strings out and concatenate them all together, so we rightly get `Dynasties in MacBeth`.

Should `SU.contentToString` change, or should a new function be added?

**Comment by alerque** [comment]
For the a few simplistic cases such as the one your show walking through the AST recursively might produce useful output, but I'm pretty sure it is also going to make a brittle command full of edge cases that don't work as intended. Some commands might inject content of their own, others might munge the content they get. You aren't going to be able to flatten this by recursivly operating on input content.

```sile
\author{\first \toupper{\last}}
```

What we probably need is something that lets all the functions do their regular thing, then extracts the final shaped nodes and concatenates their text values ... i.e. capture and concatenate strings from the output rather than trying to parse the input.

It might be possible to use the existing `text` backend for this. The way backends are instantiated needs some work to use them as modules (like the current typesetter is) but we could fire off a text only typesetter, feed it the AST, read back it's output, and be on our way...
