### ISSUE TITLE
[PDF] Table of contents destinations should be before header, not after

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1030]
When you click a TOC entry, you should also see the header. This is how e.g. Wikipedia, GitHub do it.

![image](https://user-images.githubusercontent.com/838783/90256359-77d17680-ddfa-11ea-9b17-74b0a5bfcf4f.png)

**Comment by alerque** [comment]
True that.

A quick look at the code leaves me somewhat puzzled since the bookmark location is getting set *before* the actual header is rendered.

**Comment by alerque** [comment]
Oh right, the PDF canvas coordinate system is upside down from our page-advance direction. So we need to call it after we draw not before.

**Comment by alerque** [comment]
...no it's not even that, it's just that the cursor is on the baseline where we draw from which happens to be the font's baseline too (coincidence? I think not) but the bookmark really needs to mark the height of the line that's about to be drawn. If we mark the bookmark after we draw the line we run the risk of again being too low in the case of wrapped lines. We need to hitch the cart before we have a horse. Hummm...

**Comment by ctrlcctrlv** [comment]
@alerque What about moving the cursor up `1ex`? :)

**Comment by alerque** [comment]
No need for line count, we can run it from the first line. The problem is we need line metrix. 1ex gets us the x-height of the font, we can throw a random guess of 2ex to catch most ascenders. 3ex even gives us a little (much expected) whitespace. But that feels very hacky to me. We don't have a mechanism for calculating the line height before we actually shape it, what we need is some way to stash the cursor position before we start shaping I think.

**Comment by alerque** [comment]
Oh hey we *do* know the height of the line we are in after shaping — not when we get pushed to the node queue but when we get output which is what matters.
