### ISSUE TITLE
[verbatim] \obeylines undocumented; does nothing; a working version should probably be default

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1037]
## `verbatim.sil`
```
\begin{document}
\script[src=packages/verbatim]
\begin{verbatim}
\obeylines{
Wouldn't it be nice

if this worked?
}
\end{verbatim}
\end{document}
```

![image](https://user-images.githubusercontent.com/838783/90326448-4dd49d00-df3d-11ea-98f8-fad56173b4c2.png)

SILE v0.10.10

**Comment by ctrlcctrlv** [comment]
(Also I don't much see the point of a \verbatim that allows SILE commands in it in the first place.)

**Comment by alerque** [comment]
Did you read the documentation of what `\verbatim` does? It is not meant to be a raw passthrough of all syntax, i.e. it is not an equivalent of LaTeX's similarly named `verbatim`.

![image](https://user-images.githubusercontent.com/173595/90732812-4feb8280-e2d4-11ea-89ff-7ca57b78b833.png)

It's possible that the naming is confusing for people coming from TeX, but think of it more like a `<pre>` tag in HTML.

As such embedding an `\obeylines` inside a `\verbatim` is clearly redundant and unnecessary. I would expect it to be basically a NOOP. You can see in the code the latter does the same thing anyway, the `\obeylines` is just an extraction of that one part of *verbatim*'s behavior.

I suspect the *obeylines* bit is actually working and what your actual complaint is has something to do with *parskip* not being applied. If it's not, that's something we can look into because I would expect it as well.

**Comment by alerque** [comment]
The *obeyspaces* aspect is working in `\verbatim` already, what isn't working as might be expected is *par* being applied for blank lines:

```sile
\begin[papersize=a6]{document}
\script[src=packages/verbatim]
\begin{verbatim}
Foo
Bar

Baz
\end{verbatim}
\end{document}
```

![image](https://user-images.githubusercontent.com/173595/90733813-ba50f280-e2d5-11ea-9029-ea48a6223140.png)

Note without `\verbatium` "Foo Bar" will be typeset on the same line.

Enabling it might have unintended consequence... then again parskip getting applied between every line as is currently the case is also unintended:

```sile
\begin[papersize=a6]{document}
\set[parameter=document.parskip,value=2em]
\script[src=packages/verbatim]
Foo
Bar

Baz

\begin{verbatim}
Foo
Bar

Baz
\end{verbatim}
\end{document}
```

![image](https://user-images.githubusercontent.com/173595/90736345-5d097100-e2d6-11ea-9030-a3bdbab3a699.png)

I for one did not expect parskip to have an effect between "Foo" and "Bar". The fact that it did between "Bar" and "Baz" suggests that the original bug report may actually be working 100% as intended, but not via the right mechanism.

**Comment by Omikhleia** [comment]
Relates: #2006 #2128

**Comment by alerque** [comment]
As of current versions of SILE (this was broken for a while):

1. > \obeylines undocumented; does nothing

    `\obeylines` does work, but it is not meant for use inside `\verbatim`, it changes the input parsing so that newlines are not collapsed and actually used as breaks, nothing else.

1. > a working version should probably be default

    It is now.

1. > Also I don't much see the point of a \verbatim that allows SILE commands in it in the first place.

    Use `\raw` for that use case, but there should be a default handler already setup for that and there isn't, so PR incoming to enable this usage out of the box:

    ```sile
    \begin{document}

    \use[module=packages.verbatim]
    \begin{verbatim}
    Foo \em{bar}

    Baz
    \end{verbatim}

    \begin[type=verbatim]{raw}
    Foo \em{bar}

    Baz
    \end{raw}

    \end{document}
    ```

    ![verbatim vs. raw verbatim](https://github.com/user-attachments/assets/7edc5c36-b34d-4449-a0a2-ce174a254e40)
