### ISSUE TITLE
[ruby] ruby OpenType feature should be enabled

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1047]
The Ruby package currently works by using a bold font. This normally works fine. 

However, there is an OpenType feature named `ruby` used in many single weight fonts, including one of mine, FRB Taiwanese Kana. 

The reason we often see it in single weight fonts is that it is easier to only add bold versions of the kana than to make an entire bold font. 

This is a very simple patch so I can do it myself I just want to make sure it makes sense to you guys also.

**Comment by simoncozens** [comment]
Sounds like a good idea to change the default, although users can also redefine `ruby:font` if necessary.

**Comment by alerque** [comment]
I agree changing the default to use the OpenType feature sounds like a good plan. If the workaround using Bold style is a common thing, maybe a small note can be added to the documentation (cf. §8.4.3) with a small explanation of how to use that instead.

Perhaps the default could be something like (untested):

```lua
SILE.registerCommand("ruby:font", function (options _)
  local options.size = options.size or "0.6zw"
  local options.features = options.features or "+ruby"
  SILE.call("font", options)
end)
```

Then an end user override could look like:

```lua
SILE.setCommandDefaults("ruby:font", { weight = 800 })
```

Or perhaps I misunderstood and the proposal you are making is to set both the weight and OT feature by default? That might work too, but I still suggest the option handling be twiddled so that it is possible to change the defaults like this without redefining the command from scratch.

**Comment by ctrlcctrlv** [comment]
My proposal is to interrogate the chosen font. If it has a ruby feature defined, apply it. If not, try to select bold. The reason is, even in fonts with a bold like Noto CJK, the ruby glyphs have better aesthetics.

**Comment by alerque** [comment]
Simon is better aware about that end of things, but at first blush this function isn't really getting called at a place that makes sense to setup interrogation. Even with a caching mechanism to mitigate speed issues it seems like a really clumsy point to try to branch based on font features. My first instinct is to just set the OpenType feature flag by default on the assumption that fonts used for this *should* implement that feature and only putting the best foot forward by default is okay. Then I would add the documentation note about how to deal with other cases.

**Comment by ctrlcctrlv** [comment]
Oh okay :)

**Comment by simoncozens** [comment]
I thought about introspection but it’s too much magic. You have behaviour that happens with one font but different behaviour if you run the same file with a different font. Keep it simple and just change the default.

**Comment by Omikhleia** [comment]
Regarding introspecting whether a given font has a `+ruby` feature, wouldn't the "trick" mentioned by @simoncozens in #1258 work here too:

> One way I’ve found useful to detect whether a feature exists and does something is simply to shape the same text twice, with the feature on and with it off. If the results are different, your feature did something…

For the record, I used it in [textsubsuper.sile](https://github.com/Omikhleia/textsubsuper.sile/blob/64966d0efdba719b2a212a31137c9a36174cc71c/packages/textsubsuper/init.lua#L38) to check for `+sups` etc.

**Comment by alerque** [comment]
Sure with carefully selected input to test that would work, but the caching/speed issues remain and (in my view worse) the issue of "magic" behavior remains. My vote is just change the default in the next release with an easy override to the previous behavior. Maybe a package load time option or setting.

**Comment by alerque** [comment]
I've but this issue & PR in the CJK related project, but not for bounty purposes. This particular fix is just trivial low hanging fruit I thought I'd knock out while we have a handy major release with a free chance to push in breaking changes. Arguably this wasn't even breaking since it is the *right* behavior, but some documents may need updating to render as expected so whatever...
