### ISSUE TITLE
Does SILE (intend to) support nesting `\em`?

### ISSUE THREAD

**Issue by jmaibaum** [sile-typesetter/sile#1048]
I see that SILE defines the `\em` command as follows:

https://github.com/sile-typesetter/sile/blob/f371bffab2db6d71ea3607ea34eba12a3eadc6b3/classes/plain.lua#L118

Which doesn't allow for LaTeX-style nesting of emphasis’ like:

```latex
\emph{Emphasize a \emph{word} in emphasised text.}
```

which would typeset *word* upright (again) to make it stand out from the already emphasised surrounding text. To sum up, SILE’s `\em` is more akin to LaTeX’s `\textit`, which inconditionally typesets italic text.

Is there already a SILE command to support nested emphasising? If not, would it be acceptable to change `\em` in order to support it? Or should there be another new command for this use case?

**Comment by ctrlcctrlv** [comment]
I think in this case it makes more sense to rewrite the command. Not all of the time would you want nesting to disable a command, but in this case it does make sense to me.

**Comment by simoncozens** [comment]
Yes, a command which flips the italic-ness sounds sensible to me. I'll have a play with it.

**Comment by alerque** [comment]
Given that the typical correct way to emphasis text inside emphasis is to reverse the style, changing the current function makes perfect sense. Since we only have to look at out current typesetters font stack and extract the style and toggle that value, this should be pretty straight forward.

I would also do the same thing for `\strong`, although that is somewhat less obviously the right thing to do. For people that want specifically a style or weight the `\font` command can set it directly, or we could even have `\i` and `\b` commands that specifically set the value instead of toggling it. That would more easily allow mapping to and from HTML, LaTeX, and some other source formats that make a style vs. semantic distinction in tagging data.

**Comment by ctrlcctrlv** [comment]
I would actually expect nested strong tags to increase the heaviness of the chosen font. So, one strong tag would equal bold and two strong tags would equal heavy. And if the font has an ultra, that would be three. This is how it works in HTML

**Comment by alerque** [comment]
@ctrlcctrlv I actually like the incremental weight increase, but implementation gets dicey. What if a font has a Semibold? For 95% of cases people are going to expect `\strong` to equal the *Bold* style at 700 weight. So that's a `+300` increase over 400 weight regulars. The next jump also adding `+300` doesn't make much sense. Yes asking for 1000 weight is valid and it would net you a 900 black weight if it exists, but this skips Demibold, Semibold, Extra Bold, and Heavy weights. Technically it skips Black too and goes straight to Extra Black. Making `\strong` be `+100` would be very flexible, but not very ergonomic.

Ideas?

**Comment by ctrlcctrlv** [comment]
I think it doesn't matter that much that it's a big jump. More fine grained control can be had in the normal way. The simple short tag _should_ be a big jump.

**Comment by Omikhleia** [comment]
Can we get a consensus here?
- I'd like the **original** issue to be addressed, because (usually 2-level) em-nesting occurs frequently in multilingual texts, quotes etc. See also notes below. But since in wasn't addressed before... Erm... Is there a non-obvious trap here?
- The secondary point on `\strong` is much more debatable IMHO, could it be split and discussed separately?

**Notes:**

Pandoc Markdown (e.g. `_this is an *emphasis* nesting_` ) or Djot (e.g. `_this is an {-emphasis-} nesting_`) can have nested emphasis.

Conversion to HTML yields `<em>toto <em>toto</em> toto</em>` and by default browsers use only italics here... Though tedious, alternating styles (or whatever else) may be done via CSS.

We could:
- keep our `\em` unchanged (in line with "bare" HTML, and also a non-breaking approach)
- provide an `\emph` supporting switching italics back and forth (in line with LaTeX and usual typography)

**Comment by Omikhleia** [comment]
Just for the mere record: in [https://github.com/Omikhleia/silex.sile](silex.sile 0.2.0), I changed `\em` to respect nesting.

**Comment by ctrlcctrlv** [comment]
Why not PR replacing `\em` with https://github.com/Omikhleia/silex.sile/blob/b78ac2ff97374c5bbfc77badd8925fecd6145857/silex/fixes.lua#L48 et seq?

**Comment by Omikhleia** [comment]
@ctrlcctrlv Why not indeed. But this is not the only way to go, and none of the questions in this issue got an an answer ^^
