### ISSUE TITLE
How to contribute with packages/classes to sile?

### ISSUE THREAD

**Issue by andresantosjor** [sile-typesetter/sile#1059]
I wrote some small packages in an attempt to complete my first Sile class. However, my code is subpar (at best) and I deemed it unworthy to make a pull request and integrate it to the official code. However, as they are very useful (at least for me), I wanted to share them with our small community. I visited the "Packages" page in the website but couldn't find any listing. Is there some way to link my packaging attempts where someone else could see it?

**Comment by alerque** [comment]
Probably the best thing to do for now is split your packages up into Git repositories and send a PR to the [sile-packages](https://github.com/sile-typesetter/sile-packages) repo linking to them. This will is basically a directory of people's assorted packages that they use but haven't been upstreamed into SILE's core. Some are useful to others, others may not be, but it's a good place just for your own convenience and also to get some exposure / discoverability so others could find them.

No this isn't well documented yet. Nor is the package manager really all that fully developed yet, but it's a start.

**Comment by rjmunro** [comment]
Could you maybe leverage luarocks, rather than develop your own package manager?

Cordova used to have it's own plugins, but then they switched to making plugins installable with npm and it was a huge improvement.

**Comment by ctrlcctrlv** [comment]
The packages as it were are all quite simple. You just copy the Lua file(s) into SILE's share directory. I imagine Luarocks can do this... And anyway, more complex packages might rely on Luarocks packages.

**Comment by alerque** [comment]
@rjmunro I actually suggested that (cf #538) and got vetoed before Simon implemented the current system. I've thought about it a lot more since and have more pros and cons for doing that. Luarocks does actually allow use against a third party package server (so we wouldn't have to populate the actual Luarocks site with stuff not of general interest) and quite handily it does cover installation to system, user, or local trees (a major shortcoming of the current system) as well as for multiple Lua versions. At the same time there are some downsides to using –neh hijacking– a 3rd party package manager and conscripting it to a different purpose.

Perhaps this issue isn't the best one to discuss this on though. Could be move over to №538 or a new one? See also the [Package Manager](https://github.com/sile-typesetter/sile/projects/5) project I started today to organize related issues.

**Comment by alerque** [comment]
c.f. My last comment [on related issue](https://github.com/sile-typesetter/sile/issues/324#issuecomment-1169873737). The TL;DR version is that packages and classes can now be easily be published via LuaRocks, including on luarocks.org or any other package registry.
