### ISSUE TITLE
Bringhurst class design example from the book is broken

### ISSUE THREAD

**Issue by jmaibaum** [sile-typesetter/sile#1062]
The class design example in the SILE book does not work.

Following along the text, and copy-pasting all example code into `bringhurst.lua` will result in the following error trying to use `bringhurst.lua` with this minimal document:

```sile
\begin[class=bringhurst]{document}
\end{document}
```

This is the error:

```
$ sile test-bringhurst.sil 
This is SILE v0.10.10
<test-bringhurst.sil>

! A measurement tried to measure the paper size before the paper was defined at:
	test-bringhurst.sil: in <file> (\)
stack traceback:
	/usr/share/sile/core/utilities.lua:29: in function 'core/utilities.error'
	/usr/share/sile/core/units.lua:66: in upvalue 'checkPaperDefined'
	/usr/share/sile/core/units.lua:79: in field 'converter'
	/usr/share/sile/core/measurement.lua:82: in function 'core/measurement.tonumber'
	(...tail calls...)
	[C]: in function 'lpeg.match'
	/usr/share/sile/core/frame.lua:206: in method 'isAbsoluteConstraint'
	/usr/share/sile/packages/twoside.lua:12: in function 'classes/book.mirrorMaster'
	./bringhurst.lua:31: in main chunk
	[C]: in function 'require'
	/usr/share/sile/core/sile.lua:97: in function 'core/sile.require'
	/usr/share/sile/core/inputs-common.lua:5: in field 'init'
	/usr/share/sile/core/inputs-texlike.lua:182: in field 'process'
	/usr/share/sile/core/sile.lua:246: in function 'core/sile.readFile'
	/usr/bin/sile:62: in function </usr/bin/sile:62>
	[C]: in function 'xpcall'
	/usr/bin/sile:62: in main chunk
	[C]: in ?
```

For reference, this is the contents of my `bringhurst.lua`:

```lua
local book = SILE.require("book", "classes")
local bringhurst = book { id = "bringhurst" }

bringhurst:defineMaster({
  id = "right", firstContentFrame = "content",
  frames = {
    content = {
      left = "width(page)/13",
      top = "left(content) * 8 / 5",
      right = "100%pw - 2*top(content)",
      bottom = "top(footnotes)"
    },
    folio = {
        left = "left(content)",
        right = "right(content)",
        top = "bottom(footnotes)+3%ph",
        bottom = "bottom(footnotes)+5%ph"
    },
    footnotes = {
        left = "left(content)",
        right = "right(content)",
        height = "0",
        bottom = "83.3%ph"
    },
    runningHead = {
      left = "left(content)", right = "right(content)",
      top = "top(content) - 4%ph", bottom = "top(content)-2%ph"
    },
  }
})
bringhurst:mirrorMaster("right", "left")

return bringhurst
```

**Comment by alerque** [comment]
This is an interesting issue. I think the example is missing a wrapper — that call to `defineMaster()` shouldn't just be called blindly when loading the class file, it must be called after the output is initialized. That means it needs to be part of the `init()` callback or something. Most classes dodge this bullet by not using page relative units for defining frames, but at the same thing that's something that should be possible since the page geometry will be definied at the same time as setting the class.

**Comment by alerque** [comment]
This can be solved two ways:

```diff
-      right = "100%pw - 2*top(content)",
+      right = "right(page) - 2*top(content)",
```

However I consider that a bit of a hack. The fact that the *other* page relative measurements work will come as a surprise to most users (it's a side effect of starting to define frames) and we don't want confusing things that seem to work sometimes and not others.

What I consider to be the correct thing to do here is put this sort of thing inside the correct `init()` function itself:

```lua
function bringhurst:init ()
  bringhurst:defineMaster({
  -- frame specs as usual
  })
end
```

I'll look into getting this corrected in the documentation.

I will also consider adding a warning to function(s) like `defineMaster()` if they get called directly instead of from the deferred init callback system.

**Comment by alerque** [comment]
The worning when running `defineMaster()` or similar commands other than from the deferred init callback sounded like a nice idea, but when I tried to implement it I realized that there are many legitimate uses for this. Setting up a frameset as part of class instantiation is surely the most common use case, but switching to a different frameset part way though a document is totally valid as well. Throwing noisy warnings for valid code is less than ideal too, and programmatically determining what is valid and what isn't gets pretty tricky. I think I'm going to let that idea go.

Since I've changed every single class in the SILE code and am updating the docs to match, I think the precedent for using the callback will be much clearer going forward. Anybody not following suite gets what they paid for ;-)

**Comment by jmaibaum** [comment]
Thanks for working on this issue, @alerque !

I just built the tip of your branch for #1064 and tested with this SILE file:

```sile
\begin[class=bringhurst]{document}
\script[src=packages/lorem]
\font[size=12pt]
\lorem[words=3000]
\end{document}
```

And the following `bringhurst.lua`, following your suggestions above:

```lua
local book = SILE.require("book", "classes")
local bringhurst = book { id = "bringhurst" }

function bringhurst:init()
  self:defineMaster({
    id = "right", firstContentFrame = "content",
    frames = {
      content = {
        left = "width(page)/13",
        top = "left(content) * 8 / 5",
        right = "100%pw - 2*top(content)",
        bottom = "top(footnotes)"
      },
      folio = {
        left = "left(content)",
        right = "right(content)",
        top = "bottom(footnotes)+3%ph",
        bottom = "bottom(footnotes)+5%ph"
      },
      footnotes = {
        left = "left(content)",
        right = "right(content)",
        height = "0",
        bottom = "83.3%ph"
      },
      runningHead = {
        left = "left(content)", right = "right(content)",
        top = "top(content) - 4%ph", bottom = "top(content)-2%ph"
      },
    }
  })
  self:mirrorMaster("right", "left")
  return book.init(self)
end

return bringhurst
```

The resulting PDF still looks funky: [test-bringhurst.pdf](https://github.com/sile-typesetter/sile/files/5257243/test-bringhurst.pdf)

The first page still seems to use the old master definitions, then it seems to be alternating between two page masters where one seems to be correct, but the other not. To me it looks as if something related to the `:mirrorMaster()` call is wrong.

**Comment by alerque** [comment]
Yes, that PR has been leading me down a crazy rabbit trail of problems. The fix in my comment above will work if that's the only thing you do to the example from the docs, but the PR starts digging into a myriad of other problems with the class system, particularly in defining frame sets. I just pushed some things I worked on today, but there is more to go. A whole bunch of tests are still failing and it's because the inheritance system is really goofed up. I'm getting there though.

**Comment by jmaibaum** [comment]
I will verify this again tomorrow, but I am pretty sure that the resulting PDF looks the same if I use the test and class file from my previous comment with sile 0.10.10. This is why I was trying your PR in the first place, to check if there is other stuff needed to make your new example code work. But I will happily wait with further tests if it just takes more work and time.

**Comment by alerque** [comment]
You might check again with that PR. It's passing tests now and things are in *better* shape. Not what I would call *good* shape yet, but better.

Note one of the shortcomings of the current system this mostly fixes is that all framesets were defined on top of whatever frames the parent class may have already defined. This fixes where each classes frame specs are stored to a place that can be over-ridden in each class so you can actually start with a clean frame environment. The docs are not updated to reflect this yet.

The bringhurst example should work as documented, but using that method won't inhibit the frames from the book class also being added to the document.

I didn't clean this up and document further because I noticed there are a bevy of other issues with class inheritance that I intend to fix shortly by factoring out the `stdlib` usage in favor of `Penlight`'s object inheritance system. I've been dreading this because I didn't think it could be done without breaking 3rd party code with no deprecation period, but after messing with this PR for two days I have an idea it might be possible.

**Comment by jmaibaum** [comment]
I tested again with the test documents cited above, and using the tip of your PR. This is the error I am seeing now:

```
$ sile test-bringhurst.sil 
SILE v0.10.10.r61-ga397e18 (Lua 5.4)
<test-bringhurst.sil>

Error detected:
	./bringhurst.lua:5: attempt to call a nil value (method 'defineMaster')
```

**Comment by alerque** [comment]
Since the book class no longer does a bunch of stuff via side effects loading packages when the module is loaded rather than during `init()`, you need to actually load the packages you want to use into the class yourself. Here is the full `bringhurst.lua` I just checked with, note the two `self:loadpackage()` lines are additions to the example above:

```lua
local book = SILE.require("book", "classes")
local bringhurst = book { id = "bringhurst" }

function bringhurst:init()
  self:loadPackage("masters")
  self:defineMaster({
    id = "right", firstContentFrame = "content",
    frames = {
      content = {
        left = "width(page)/13",
        top = "left(content) * 8 / 5",
        right = "100%pw - 2*top(content)",
        bottom = "top(footnotes)"
      },
      folio = {
        left = "left(content)",
        right = "right(content)",
        top = "bottom(footnotes)+3%ph",
        bottom = "bottom(footnotes)+5%ph"
      },
      footnotes = {
        left = "left(content)",
        right = "right(content)",
        height = "0",
        bottom = "83.3%ph"
      },
      runningHead = {
        left = "left(content)", right = "right(content)",
        top = "top(content) - 4%ph", bottom = "top(content)-2%ph"
      },
    }
  })
  self:loadPackage("twoside", { oddPageMaster = "right", evenPageMaster = "left" })
  self:mirrorMaster("right", "left")
  return book.init(self)
end

return bringhurst
```

**Comment by alerque** [comment]
Working on the docs for this change several simplification occured to me. You can actually use this as the (whole) `brighthurst.lua` class file and get the same effect:

```lua
local book = SILE.require("book", "classes")
local bringhurst = book { id = "bringhurst" }

bringhurst.defaultFrameset = {
  content = {
    left = "width(page)/13",
    top = "left(content) * 8 / 5",
    right = "100%pw - 2*top(content)",
    bottom = "top(footnotes)"
  },
  folio = book.defaultFrameset.folio,
  runningHead = {
    left = "left(content)",
    right = "right(content)",
    top = "top(content) - 4%ph",
    bottom = "top(content)-2%ph"
  },
  footnotes = book.defaultFrameset.footnotes
}

return bringhurst
```

The book class' init function takes care of all the setup already, nothing special needs to be done and there is no sense in repeating everything.

**Comment by alerque** [comment]
Thanks for reporting this @jmaibaum, and for continuing to test it. I think the example should work as documented now. I'm going to merge the PR as is for now and get to work on replacing the Lua class (object) model used by the class (Lua document) system with Penlight instead of stdlib.

**Comment by jmaibaum** [comment]
Hi @alerque thanks for your speedy work. I have just tested the rephrased example code from the book for SILE 0.10.11, and it does work for the right page master now, but the left page master seems to be unchanged: [test-bringhurst.pdf](https://github.com/sile-typesetter/sile/files/5286762/test-bringhurst.pdf)

**Comment by alerque** [comment]
Bumping the real permanent fix for this to the release that I expect the stdlib→Penlight transition to happen for document classes.

**Comment by alerque** [comment]
I recently rewrote the bringhurst example in the manual. I also tried copy/pasting it from the PDF and setting up a test document. The example itself works but has *always* been self referential gibberish. The mirroring did not work as expected because values were defined relative to themselves, which obviously changed from page to page. The mirroring was actually working, but with the left edge being relative to the top and the top being relative to the left edge the right master obviously looked different than the left.

A fix for that in the manual is incoming too.
