### ISSUE TITLE
PDF TOC entries are TOFU

### ISSUE THREAD

**Issue by indiamcq** [sile-typesetter/sile#1132]
When I download the documentation PDF, I open the bookmarks and the text is all tofu square boxes.

(Edit: Moved second issue to #1155)

**Comment by alerque** [comment]
Thanks for the report. I can confirm the ToFu issue. I'm not sure where that regression cropped up but we'll look into it.

This issue is really two completely separate issues with different fixes that should be tracked separately. Lets keep this one about the PDF ToC encoding bug. Can I ask that you open a separate feature request issue for adding hyperlinks to pages from in-document ToC?
