### ISSUE TITLE
SILE wrongly assumes a space will never contain any shapes, resulting in bizarre output

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1146]
![image](https://user-images.githubusercontent.com/838783/108014206-62245000-6fdb-11eb-9c72-6747a8880881.png)

Those spaces shouldn't be there.

File: https://github.com/ctrlcctrlv/FRBAmericanCursive/blob/main/specimens/combos.sil

**Comment by simoncozens** [comment]
This *almost* gets you there, except it emits the spaces in red...

```

SILE.settings.declare({
  parameter = "shaper.complexspaces",
  default = true,
  type = "boolean",
  help = "Whether the font's space glyph should be emitted, rather than a glue"
})

local origSpaceNode = SILE.shaper.makeSpaceNode

SILE.shaper.makeSpaceNode = function (_, options, item)
  if SILE.settings.get("shaper.complexspaces") then
    items, width = SILE.shaper:shapeToken(" ", options)
    nnode = SILE.shaper:formNnode(items, " ", options)
    return SILE.nodefactory.discretionary({replacement={nnode}})
  end
  return origSpaceNode(_, options, item)
end
```

**Comment by simoncozens** [comment]
This *does* get you there, but is ugly:

```
SILE.nodeMakers["x-spaces-are-nodes"] = pl.class({
    _base = SILE.nodeMakers.unicode,
    makeGlue = function (self, item)
      self:addToken(" ", item)
      self:makeToken()
    end
})

SILE.languageSupport.languages["x-spaces-are-nodes"] = true

SILE.settings.declare({
  parameter = "shaper.complexspaces",
  default = true,
  type = "boolean",
  help = "Whether the font's space glyph should be emitted, rather than a glue"
})

local origSpaceNode = SILE.shaper.makeSpaceNode

SILE.shaper.makeSpaceNode = function (_, options, item)
  if SILE.settings.get("shaper.complexspaces") then
    myoptions =  pl.tablex.deepcopy(options)
    myoptions.language = "x-spaces-are-nodes"
    nnodes = SILE.shaper:createNnodes( " ", myoptions)
    return SILE.nodefactory.discretionary({replacement=nnodes})
  end
  return origSpaceNode(_, options, item)
end
```

**Comment by alerque** [comment]
Not about this issue *per se*, but just a quick not about your `combos.sil` file: the `\par` command in SILE should be issued *after* content to end a paragraph, not before content to start one. In 99% of the lines of that file the difference is moot because it comes between paragraphs whether you write it and the beginning ond end of a line, but I think the coding style and subtle difference is tripping you up in the 1%. For example you are ending up with things like `stuff\eject{}\par{}stuff` instead of `stuff\par{}\eject{}stuff`. In some cases this will screw up your page layouts. I suggest getting used to writing `\par` trailing the end of content lines instead of prefixing them and those subtle difference won't crop up as much.

Here is the definition of `\par`:

```lua
SILE.registerCommand("par", function (_, _)
  SILE.typesetter:endline()
end, "Ends the current paragraph.")
```
