### ISSUE TITLE
Can we have a -q (--quiet) flag?

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1165]
A flag that would stop the printing of e.g.

```
SILE v0.10.15.r22-g72548c8-dirty (Lua 5.4)
</tmp/eachfontFRBAmericanCursive-800-GuidelinesArrowsExtrabold.otf.sil>
[1]
```

But unlike redirecting stderr to /dev/null, will still print errors.

**Comment by alerque** [comment]
That does sound like a good idea.

What about warnings?

**Comment by ctrlcctrlv** [comment]
Logic could be:

* if `-q` is present, quiet all except errors
* if `-q` receives a member of the set `(debug, info, warnings, errors)`, quiet messages below the provided string. (No need to make it possible to quiet errors as that's identical to stderr redirection.)

**Comment by alerque** [comment]
Fixing this properly will involve sorting through most of the code and places where output of any kind is given. This work would probably go well with an overhaul of how the debug and messaging functions work technically. See also #756.

**Comment by Omikhleia** [comment]
I am going to feel sorry again for writing this... But what is the "good idea" here? What problem would it address, or solve?

**Comment by alerque** [comment]
One of the really frustrating things about using LaTeX on big projects is how hard it is to sort through the reams and reams of noisy output for what actually went wrong. SILE has been getting noisier and noisier in a way that just clutters the terminal without being helpful. The output can be helpful when developing some bit, but most of the time it just serves to disorient. Even knowing SILE inside and out I have trouble scanning my CI jobs, hence once reason why CaSILE buffers SILE's terminal output and only displays it if there is a problem else not at all.

The good idea here is debug / error / warning / info / notice levels of data should be configurable. This will serve both novice and advanced users alike, if for different reasons.

**Comment by alerque** [comment]
I'm fully away #1759 is a sub-optimal fix–kind of a sledge hammer when what was ordered was a set of wrenches in 1mm increments–but since the "feature" is end user convenience candy and there are several blockers to doing a better overhaul I figured it was worth starting with the simple solution. Part of the problem is our CLI args parser doesn't support optional values *or* multiple counts of the same flag. Beyond that we don't have all our output broken down quite cleanly between debug/info/warning/error levels. We do have the top end of that already pretty well isolated, so for now `--quiet` mode is just going to suppress *everything* except errors.
