### ISSUE TITLE
Getting the PPA to also provide builds for jammy, the upcoming Ubuntu LTS 22.04

### ISSUE THREAD

**Issue by n7s** [sile-typesetter/sile#1312]
It would be fantastic to have the PPA for Ubuntu users provide SILE and its dependencies for jammy (upcoming LTS due to be released in 22.04). Thanks!

**Comment by alerque** [comment]
Roger that.

I actually haven't gotten the last release built (#1310) for *any* Ubuntu variant yet because I ran into trouble with by LXC containers I usually use for the job. I'm now trying to automate creating them and using them for release bumps but am stuck on my GPG agent not giving the script in the container access to sign uploads.

In any event I'll leave this open until Jammy builds are available. No promises about not ranting further about how much I hate Ubuntu.

**Comment by alerque** [comment]
Good news on the progress here. I now have a script that orchestrates creating LXD containers, installing deps, building deb source packages, and posting them to the PPA. The most serious crime committed along the way is having to type my GPG key passphrase enough times to pave a road to Mordor (and *maybe* having typed it into some non-tty's by accident along the way).

Some dependencies are building now, hopefully sile will follow when that groundwork is in place. It's a little tedious because launchpad caching has to clear in between builds since the containers are completely reliant on what has made it to the CDN for their deps.

**Comment by alerque** [comment]
I think all the work is done and builds are setup for all of the Ubuntu release zoo, but I'm still waiting to trigger some rebuilds. At the moment I'm 24 deep in "pending" jobs on Launchpad and some of them are throwing disk space errors which can only be a problem with their build farm. I think I'm going to have to let the dust settle and come back to see how far it gets.

**Comment by alerque** [comment]
Done. Impish and Jammy both have up to date sile packages in the PPA with all deps.

Let me know if you run into trouble with Penlight. It looks like a current version is tracked for inclusion in Jammy, so we're going to have a bit of a fiddle with that since it will be newer than our build when the LTS ships and then undoubtedly older again in short order (since Penlight release cycles are faster than Ubuntu LTS!). I just left it in for now but if we need to pull it when the LTS is cut to avoid "newer than X" errors I'll adapt.
