### ISSUE TITLE
SILE.typesetNaturally is broken

### ISSUE THREAD

**Issue by khaledhosny** [sile-typesetter/sile#1317]
```
\begin[direction=RTL]{document}
\font[family=Amiri,size=100pt]
\nofolios

\begin{script}
SILE.typesetNaturally(SILE.getFrame("content"), function()
 SILE.typesetter:typeset("عَرَبي")
end)
\end{script}

\par

\begin{script}
SILE.typesetter:typeset("عَرَبي")
\end{script}
\end{document}
```

The first line here is broke, the second line is not.
<img width="402" alt="image" src="https://user-images.githubusercontent.com/93914/155447887-d1467f59-6585-433e-9938-b778aa7c50b3.png">

The line resetting the typsetter to the `SILE.defaultTypesetter {}` seems to be the culprit:
https://github.com/sile-typesetter/sile/blob/58b54ec78df6290e7d5860578bbb61654e5d3e9a/core/typesetter.lua#L721-L729

No idea of this intentional or not, but it breaks things like `\typeset-into` from `frametricks`.

**Comment by alerque** [comment]
I thought this was going to be a simple fix for a blooper bug, but my first few stabs at fixing it haven't netted the result I expected. Bafflingly I have yet to find anything different in the settings, frame state, typesetter state, node queues, or anything else relevant. I assigned myself because I was working on this but I'm out of time for today, if anybody wants to take a stab at it it might be a day or two before I can poke this again.

**Comment by alerque** [comment]
Not 100% relevant to this being a big, bug can I ask what the use case is for using `typesetNaturally()` into the same frame it is called from?

Also small point, but `\par` is totally unnecessary and potentially harmful in situations like this MWE, this isn't TeX ;-)

**Comment by alerque** [comment]
Maybe not useful to anybody but me, but so I have it on the next computer I stashed some of my debugging attempts here: https://github.com/alerque/sile/commit/2709f3d69eb4cce54c43796cf0a64531c2a748cb

**Comment by alerque** [comment]
Found it. When the initial document class is told to setup an RTL frame it loads the bidi package. The bidi package makes changes to the *current* typesetter. Instantiating a new default typesetter looses the changes that loading the bidi package made.

I'll have to think a little bit about what the best solution is, but at least the problem is clear to me now.

**Comment by simoncozens** [comment]
Bidi processing should be default, really. Can we make it alter the default typesetter instead?

**Comment by alerque** [comment]
Yes, that was already my first idea too.

**Comment by alerque** [comment]
A *proper* fix to this will have to wait for the Penlight refactoring that is *still* in progress. Ideally instantiating typesetters should be done with a working inheritance model like we started (and got kind of stuck) for document classes. The `stdlib` based model just doesn't have the tools to handle this more elegantly than just patching the default object being copied by everybody.

The other thing is we shouldn't be blinding typesetting stuff into a frame without considering anything that might already be typeset into that frame (as it is currently doing). My idea would be to link a typesetter instance from the frame and re-use it if asked to output more content to the same frame. However that too requires some inheritance stuff that –if done now– will just clog up the Penlight transition. Yes I should get back to that.

**Comment by khaledhosny** [comment]
> Not 100% relevant to this being a big, bug can I ask what the use case is for using `typesetNaturally()` into the same frame it is called from?

This was just to produce a MWE. In my actual document, I’m typesetting the same text in three frames, each with a different font size. I’m trying to do this without having to copy and paste the text each time (I have to repeat this for a lot of sample texts).
 
> Also small point, but `\par` is totally unnecessary and potentially harmful in situations like this MWE, this isn't TeX ;-)

I have been superstitiously adding `\par`s left and right, because otherwise pad things I can’t explain happen, and I‘m trying to learn too much things about SILE in a limited time, so all I care about right now is getting the document looking the way I need it too look, no matter what bad things I end up doing. Fortunately, this is done, so I can try to clean it up and make it more idiomatic or whatever later. I’m glad SILE exists, and though finding answers can be frustrating at times, at least I don’t have to do this in TeX!

**Comment by khaledhosny** [comment]
> In the mean time if you want to move on with using the functionality you can include a monkey-patched replacement by just redefining the global `SILE.typesetNaturally()` function early on in any Lua script block or include for your project as follows:

This works, thanks.

**Comment by khaledhosny** [comment]
FWIW, I have the exact same issue with `linespacing` package, I need to do `SILE.typesetter.leadingFor = saveTypesetter.leadingFor` or the linespacing settings will not be applied.

**Comment by alerque** [comment]
Yes, but for linespacing that is expected. The whole point is it should be instantiating a new typesetter with all default settings. The problem with BiDi was it was supposed to be on by default. Your linespace setting changes are not defaults hence it would be expected to need to include those settings you want *inside* the content function callback passed to typesetNaturally().

If anything the fact that the font and font size were inherited (because they are not scoped to the typesetter) is unexpected and probably should be considered a bug.
