### ISSUE TITLE
justenoughicu.so not installed via make install

### ISSUE THREAD

**Issue by IcedQuinn** [sile-typesetter/sile#1353]
Hello,

I've installed `v0.12.3` from Git successfully on Void Linux. However the makefile installs a version of the software which does not work as `justenoughicu.so` is not installed to a valid directory. If you manually install this to one of the lua dependency folders in /usr/local it works great though.

Seems like a slight accident in the makefile.

**Comment by alerque** [comment]
Thanks for the report. I'd be happy to fix this if we can track down what is actually wrong. In general the makefile's *do* place this file (Arch Linux, Ubuntu, Nix, Homebrew, and others all rely on it for their packaging). That's not to say some idiosyncrasy isn't causing it to be skipped in your case, just that it's not an obvious cut and dry thing. Honestly though that part of the build is kind of a relic from early days of SILE and a little crusty.

I had a look and one possibility is the "tell" system where stuff is built in one place, and then a marker placed to say whether those things were done, then the marker used to know whether to run that build again. The marker seems to assume all of the builds ran if one of them did.

Is it possible you aborted one `make` run incomplete but having build *some* of the sources, then reran it again to finish up? That's one scenario I see *might* lead to the effect you are describing.

By the way when we do get this working from source I'd love to revive the Void Linux packaging effort. It got stalled out a long while back because I needed more Lua dependencies than I knew how to setup for Void, but there is a now outdated package and [this attempt to update it](https://github.com/void-linux/void-packages/pull/18306). If somebody with some knowledge or access to Void packaging is willing to help I'd jump in to facilitate that getting brought up to date.

**Comment by alerque** [comment]
Also possibly useful to know...

After you successfully `./configure`, does `make selfcheck` work for you?

**Comment by alerque** [comment]
I'd like to resolve this before the next release, but since I am unable to replicate the problem and I haven't gotten any further information from you about what does and doesn't work I make not be able to do anything. Just a friendly poke to say I'll act on this if/when I get info...

**Comment by alerque** [comment]
Never mind, I've been able to replicate something *similar* at least on BSDs where the SILE_LIB_PATH will have `/usr/local/lib` while the library actually gets installed to `/usr/local/lib/sile` when using default compile and install options. That may be enough to go on to come up with a fix...

**Comment by alerque** [comment]
Fix is in #1354, see comment there for an explanation.
