### ISSUE TITLE
Do leaders (dotfill) without content on both side behave correctly?

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1426]
SILE 0.12.5 and 0.13.0

I wonder what is the expectations for `\leaders` (thus, indirectly, `\dotfill`) when there is not some content on both sides, that is when the leaders stands at the beginning or at the end of the line (and thus, obviously, also on their own line alone).

**Input scenario**
```\begin[papersize=a6]{document}
\nofolios
\neverindent
\script[src=packages/leaders]
BEGIN

A\dotfill

A\dotfill{}B

\dotfill{}A

\dotfill

END
\end{document}
```

**Current behavior**

![image](https://user-images.githubusercontent.com/18075640/173243754-54985bf6-7a61-4b40-9fa1-1b182f0a61dc.png)

Note that the current code actually inserts the leader in the typesetter queue in a raw (low-level) direct way:
```
    table.insert(SILE.typesetter.state.nodes, l)
```

**Behavior with pushGlue**

Since the leaders are a glue node, we could have been tempted to use the more usual `SILE.typesetter:pushGlue(l)`

![image](https://user-images.githubusercontent.com/18075640/173243900-4943420a-7657-4b4c-b6fb-8d33f1ac0279.png)

**Behavior with pushExplicitGlue**

But we could also have it non-discardable, using `SILE.typesetter:pushExplicitGlue(l)`

![image](https://user-images.githubusercontent.com/18075640/173244032-73d004f5-17b4-419f-80fc-d1e3e2f05886.png)

I wonder what's the more "expected" result here... I would have, personally, thought the third one to be what I intended... But I might be missing other use cases? Also, these examples might not be very frequent (e.g. when used in a ToC, one has both an element before and after the dots, usually!). There could have been a good reason for this... Yet, it kind of annoys me, and it looks as a discrepancy with `\hfill`, which does push an explicit glue.

**Comment by alerque** [comment]
My expectation as and end user would have been the third one too. Unless we know of a specific use case for something else lets go with that.

And yes, using the `typesetter:pushX()` methods should be the way to implement this. If the existing API does not service I suggest we fix the API rather than doing the manual table munging (even if it works). That way we have the option in the future to, for example, swap out the typesetter function with a Rust implementation that is 10× faster. We will only be able to swap out implementations of bits where the used surface is the API methods. Anything reading inside mucking with the data it assumes is there will be a blocker.
