### ISSUE TITLE
Installing with homebrew is not as easy as advertised

### ISSUE THREAD

**Issue by rjmunro** [sile-typesetter/sile#143]
This post: https://github.com/simoncozens/sile/blob/gh-pages/_posts/2015-06-26-SILE-is-now-in-homebrew.md implies `brew install sile` _should just work_...

I get:

```
 $ brew install sile
sile: Unsatisfied dependency: lpeg
Homebrew does not provide Lua dependencies; install with:
  luarocks install lpeg
sile: Unsatisfied dependency: luaexpat
Homebrew does not provide Lua dependencies; install with:
  luarocks install luaexpat
sile: Unsatisfied dependency: luafilesystem
Homebrew does not provide Lua dependencies; install with:
  luarocks install luafilesystem
Error: Unsatisified requirements failed this build.
```

Then:

```
$ luarocks install lpeg
-bash: luarocks: command not found
```

**Comment by alerque** [comment]
Homebrew is missing full support for Lua dependencies. When I [initially submitted the SILE formula](https://github.com/Homebrew/homebrew/pull/40893) I included code that manually installed the luarocks. On a [subsequent update](https://github.com/Homebrew/homebrew/pull/41288) I was actually asked to remove that because it broke the way they are building pre-compiled binaries (bottles) and distributing those instead of having target systems run the package. The homebrew team's current preferred solution is to abort and manually prompt for those installations.

The result right now is definitely sub optimal and I've been looking into solutions, but I'm not sure it's going to be possible without homebrew's bottle system getting new support added. One alternative is to provide a 3rd party "tap" that you could install from directly without extra commands. The other is trying to rally support for getting the Homebrew crew to fix the bottle system on their side.

In the mean time since your system doesn't seem to have Lua at all, try this  sequence

    $ brew install lua
    $ luarocks install lpeg
    $ luarocks install luaexpat
    $ luarocks install luafilesystem
    $ brew install sile

If that doesn't do the trick please let me know so I have a better idea of what we are up against.

**Comment by rjmunro** [comment]
Installing Lua worked, but gave a warning "...any binaries installed via Luarocks-5.2 AND 5.1 will overwrite each other in /usr/local/bin." I'm sure that doesn't matter.

But:
```
$ luarocks install lpeg
    
Error: @@HOMEBREW_PREFIX@@ does not exist and your user does not have write permissions in  
-- you may want to run as a privileged user or use your local tree with --local.
```
Note that it says "write permissions in " and doesn't specify anything - that's not a copy and paste mistake. That sounds like a bug in the lua brew - presumably it was supposed to expand `@@HOMEBREW_PREFIX@@` into `/usr/local/` or something during setup. Someone else has reported this here: http://stackoverflow.com/questions/31671134/unable-to-install-package-using-luarocks-on-osx

From SILE's point of view the fix is probably just to remove the text "... the easiest way to install SILE is now ... brew install sile" from the home page :smile:.

**Comment by simoncozens** [comment]
Shouldn't be necessary of course, but try a `brew sh` before running the `luarocks install ...` commands to get a correct Homebrew dev environment?

**Comment by alerque** [comment]
@rjmunro Are you on the El Capitan beta?

**Comment by rjmunro** [comment]
Sorry, I wasn't very clear. The problem is that `brew install lua` has given me a /usr/local/etc/luarocks52/config-5.2.lua that looks like:
```
rocks_trees = {
   { name = [[user]], root = home..[[/.luarocks]] },
   { name = [[system]], root = [[@@HOMEBREW_PREFIX@@]] }
}
```
I suspect brew was supposed to substitute `@@HOMEBREW_PREFIX@@` when it installed it (unless `@@VARIABLE@@` is lua for environment variable or something).

**Comment by rjmunro** [comment]
@alerque No, Yosemite 10.10.3

**Comment by rjmunro** [comment]
Changing `@@HOMEBREW_PREFIX@@` to `/usr/local` in `/usr/local/etc/luarocks52/config-5.2.lua` has fixed it, but that's not something I should have to do.

**Comment by DomT4** [comment]
> Changing @@HOMEBREW_PREFIX@@ to /usr/local in /usr/local/etc/luarocks52/config-5.2.lua has fixed it, but that's not something I should have to do.

This was a bug in the way we relocate text files, and was fixed this morning. If you remove the existing configuration file & `brew update && brew reinstall lua` the problem should not reoccur.

**Comment by alerque** [comment]
@DomT4 Thanks for the feedback on the other Homebrew issue playing into @rjmunro's installation problem!

**Comment by DomT4** [comment]
What I said in the Homebrew thread on this:

> Requiring modules to be installed before installation is somewhat tricky behaviour, and upstream would make our lives significantly easier if instead of checking for those modules during configure they'd move that check into the executable, so instead of breaking during configure it'd install and then on run throw a message like `You need to install xyz module`. If that was the situation, we could hack together some sort of `postinstall` solution which would do something like `luarocks install xyz` for the user (Resolving your immediate issue/concerns).

The broader discussion is in https://github.com/Homebrew/homebrew/issues/42273. I've started making some very minor changes to the way we handle Lua, which should at least make it clear how to not wander into the `-bash: luarocks: command not found` confusion relatively soon.

**Comment by simoncozens** [comment]
Any update on this from Homebrew users? The referenced upstream bug says "Closing old usability issues in favour of pull requests", which reminds me of the [CADT Model](https://www.jwz.org/doc/cadt.html).

**Comment by rjmunro** [comment]
Here's what happens now:
```
$ brew install sile
sile: Unsatisfied dependency: lpeg
Homebrew does not provide special Lua dependencies; install with:
  `luarocks-5.2 install lpeg`

You may need to: `brew install lua`

sile: Unsatisfied dependency: luaexpat
Homebrew does not provide special Lua dependencies; install with:
  `luarocks-5.2 install luaexpat`

You may need to: `brew install lua`

sile: Unsatisfied dependency: luafilesystem
Homebrew does not provide special Lua dependencies; install with:
  `luarocks-5.2 install luafilesystem`

You may need to: `brew install lua`

Error: Unsatisfied requirements failed this build.
```
The improvement is that is now says "You may need to: `brew install lua`", which is helpful.

The full instructions are therefore:
```
brew install lua
luarocks-5.2 install lpeg
luarocks-5.2 install luaexpat
luarocks-5.2 install luafilesystem
brew install sile
```

**Comment by alerque** [comment]
Thanks for the update @rjmunro, it's hard to test this because I don't have a clean OSX system to experiment with. I'll look into updating the instructions on our side.

There are a couple things that should actually be added to that list for upcoming SILE releases, specifically the luarocks for `cosmo` and `zlib`. They won't matter unless you are installing `--HEAD`, but those plus `icu` are new requirements in the development version.

**Comment by DomT4** [comment]
It's still not ideal, but yeah, I made a few small improvements to the messaging a while back.

Ideally there would actually be a system in place to not require lua modules to be installed globally but rather stored within the prefix in the same way `python` stuff is handled, but I've since left the project, so someone would need to pick that work up & get it past the lead maintainer.

**Comment by alerque** [comment]
There is an open [Pull Request](https://github.com/Homebrew/homebrew-core/pull/35960) for updating sile in homebrew. Hopefully that will tidy off lose ends in this issue!

**Comment by alerque** [comment]
The last few releases to Homebrew have been pretty smooth. The way Lua dependencies are handled is completely different than it used to be. I think it really is as easy as advertised now. If not anyone having trouble with it is kindly requested to open a new issue with specifics.
