### ISSUE TITLE
localization issues 

### ISSUE THREAD

**Issue by rolfmblindgren** [sile-typesetter/sile#1466]
I'm using the homebrew distribution.

With sile 0.13.2  (but also the previous versions of sile), this 

`\font[family=Sabon LT Std,language=no]`

give the error message

`! Error loading localizations no: no localizations for this language at adhd.sil:2:1: in \fonttable: 0x60000232e6c0`

However, there seems to be provisions for `no` in the distribution:

`/opt/homebrew/Cellar/sile/0.13.2/share/sile/languages/no.lua` contains hyphenations patterns.

`\language[main=no]` gives the same error message.

What am I missing?

Any and all hints and suggestions appreciated.

**Comment by alerque** [comment]
Thanks for reporting this. I believe the issue is just one of confusing messages, but I see they could use improvement.

1. First of all, the thing you see is a *warning* not an error, and that should be clarified.
1. Next it's worth clarifying that the different between "localizations" and "language support".

Yes there is language support including hyphenation patters for `no`. This allows it to properly typeset text in that language. What is missing are the localized strings that SILE might need to add to a document on your behalf. This includes a handful of things such as the word translation of "Chapter" to prefix "Chapter 1" and the phrase "Table of Contents" to put at the top of a TOC. There are not very many of these strings and they are *not* required to function, this warning is just a heads up that they are not available.

If they did exist they would be in the file `.../share/sile/i18n/no.ftl`. As you can see [that file does not exist](https://github.com/sile-typesetter/sile/tree/master/i18n). If by chance you are able to translate that handful of strings for us I'd be happy to include them in the next SILE release. Also you can easily add or override those strings in your own libraries or documents using the `\ftl` command.

```sile
\ftl[locale=no]{toc-title = Foo Bar}
```

(where "Foo Bar" is of course whatever the `no` localized string should be!)

**Comment by Omikhleia** [comment]
FWIW, if using the appropriate generic patterns from TeX, "nb" (Bokmal) and "nn" (Nynorsk) are the only two _written_ forms specified by ISO 639 -- with "no" being a generic country code IIRC, often assumed to mean "nb"). They can have the same pattern files, with a few differences handled via hyphenation exceptions.

**Comment by alerque** [comment]
The [current collection of strings being localized](https://github.com/sile-typesetter/sile/blob/master/i18n/en.ftl) stands at 8, and one of them is literally "hello world" (used it tests) and another is simply "and". It shouldn't be a huge burden. I expect there might be a couple addition as time goes on (e.g. "Section" and "Part" in addition to "Chapter" and perhaps "Figure X", etc.) but there are good reasons *not* to automatically be stuffing a bunch of strings in people's output, so I don't expect this to grow much.

As for differentiating between locales with both a language and region identifier instead of just a language, we're not quite there yet but we know about the problem. SILE kind of started off conflating language, script, locale and we're still trying to un-conflate them (c.f. #1367, #1368 and linked issues).

We don't *yet* have region code parsing happening with fallbacks to base locales yet, but we have most of the tooling to do so if need arises. We currently only have one set of support patterns for `no`, but if you come up with others (for example different hyphenation patterns) and get it working the way a specific region should be by modifying using just `no` then I'd be willing to finish off refactoring language values to be locales to support that.

**Comment by rolfmblindgren** [comment]
no.ftl

hello = Hei { $name }!
toc-not-generated = Kjør SILE om igjen slik at innholdsfortegnelsen blir behandlet!
toc-title = Innhold
book-chapter-title-pre = Kapittel{" "}
bibliography-and = og
bibliography-edited-by = Redigert av { $name }
bibliography-et-al = et al.
bibliography-translated-by = Redigert av { $name }

--
Rolf Lindgren
+47 455 19 940
http://www.grendel.no/

**Comment by alerque** [comment]
Thanks for the contribution. Expect to see those strings (and more informative warning messages) in the next release.

Are there hyphenation rule differences between the Norwegian variants that we should pursue?

Full support for region codes will come at some point (even if they are largely ignored for our purposes) but if there was something specific we needed to support we could look into dealing with it sooner rather than later.

**Comment by rolfmblindgren** [comment]
this is hyph-nn.tex

input hyph-no.tex

\hyphenation{
att-en-de
bet-re
}

so, no, not a lot.


--
Rolf Lindgren
+47 455 19 940
http://www.grendel.no/

**Comment by alerque** [comment]
Just two exceptions? We can handle that. I just added support for `nb` and `nn` languages, mostly inheriting from `no` with those exceptions added. Whatever I or "some" may think we don't have the flexibility to rearrange languages the way we want or name them however we feel like because we're validating against Unicode CLDR data. So far no region variant support, just the `no`, `nb`, and `nn` language codes.
