### ISSUE TITLE
Programmatic use of lower breaks (raiselower package)

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1504]
**Test scenario**
```
\begin[papersize=a6]{document}
\use[module=packages.raiselower]

Text\lower[height=0.5ex]{lowered}% OK

Text\lua{SILE.call("lower", { height = "0.5ex" }, { "lowered" })}% OK

Text\lua{SILE.call("lower", { height = SILE.length("0.5ex") }, { "lowered" })}% OOOPS
\end{document}
```
**Observed results**
When compiling, the last case (marked OOOPS) generates:
```
Error detected:
	./packages/raiselower/init.lua:28: attempt to concatenate a table value (field 'height')
```
**Analysis**
At some point in 0.13 (IIRC), some "string" shims were removed, that allowed `SILE.length` (or `SILE.measurement` etc.) to support automatic conversion to string -- leading to this regression (though the code concatenating a minus char to the provided height option had some smell ;) 

_Issue found when upgrading some 0.12.5 code (#1503) where I use computed lengths in Lua code - so it likely means there's no existing test coverage for it._

**Comment by alerque** [comment]
`SILE.length` and `SILE.measurement` can still be automatically converted to strings, the most impactful shim that got removed when dropping luastd changed how Lua handles concatenating `nil`. If a variable can be nil rather than a string (or number/table that can be cast to a string) you now need to explicitly `tostring(variable)` which will return a string `"nil"`.

I can probably track down where this one is buried...

**Comment by alerque** [comment]
For some reason these functions were expecting a frame dimension (potentially parsed with the likes of `height(frame_id) / 2`) rather than something to parse as a SILE.measurement. Given we have frame-relative units like `%fh` now it seems like this is probably an obsolete hack to get friendly input styles. It predates the measurement/length objects by quite a bit (a02848e83 in 2014). I'm dropping that and just parsing them as `SILE.measurement`. I couldn't think of a use case for them being `SILE.length`s. Feel free to correct me if you can think of one.
