### ISSUE TITLE
Booklet package

### ISSUE THREAD

**Issue by pingiun** [sile-typesetter/sile#1525]
I'm not sure if this is possible but it would be useful to add a package which sets 2 smaller pages on 1 bigger page such that you can send it to a printer with double-sided printing and be able to fold it like a booklet. This also requires the pages to switch positions in the pdf, such that the last page is on the left side of the first page etc. I'm not sure if this is possible in SILE because of the page positions switching after rendering.

**Comment by alerque** [comment]
I've thought about this before, but logistically the best way to implement this is to render all the smaller pages and then later come back and iterate over them and stuff them in a larger layout. As such anything SILE did in this area would basically be re-implementing other tooling. I do booklet printing like this on a significant scale every week, but the best workflow I've found is to generate the content (in my case mixes SILE & LaTeX because I haven't finished a Lilypond package for SILE yet) and then post-process it with sme combination of `pdftk`, `cpdf`, and `pdfbook2`. Since I usually do A5 pages composed as booklets on A4 paper designed to be duplex printed and folded, except in the cases where I need to use a subset of pages (I usually reach for `pdftk`) or crop odd/even pages differently (I usually reach for `cpdf`) I can skip any other processing and just use `pdfbok2 --short-edge -- input.pdf`.

I'm open to hearing more use cases, but I'm reluctant to start adding in stuff like this kind of post processing that is already done well by other tools.

**Comment by Omikhleia** [comment]
I concur with @alerque that better tools exist for that task, once one has a PDF.
I remember the old days when I was using the "[quire](https://www.ctan.org/pkg/midnight)" package for plain-TeX for that exact purposed, and hacked it (with changes now lost...) to make it work properly with LaTeX2e. It was hard to trick some of the output methods to make it still work, as far as I can remember - And I've no idea how it would have behaved nowadays with other TeX engines (pdflatex, lualatex etc.)... Probably tricky to maintain properly!
On the other hand, existing tools such as `pdfbook2` offer plenty of additional options and complex re-assembling layouts for "paper folding" (i.e. not only the 2 to 1 folding discussed here). These are probably the way to go, _after_ SILE has generated a standard PDF, rather than some very tricky way to change SILE's output routines to reorder pages, no?

**Comment by alerque** [comment]
> These are probably the way to go, _after_ SILE has generated a standard PDF, rather than some very tricky way to change SILE's output routines to reorder pages, no?

We would never bother changing the output routines to reorder pages, we'd just stash the whole thing in memory and re-order them after rendering everything. Even the way LaTeX handles this now (my experience is more modern than *quire* but has the same feel) is by post-processing and embedding smaller PDF pages as images in larger ones. It doesn't try to generate them in place.

Two more points:

* Many printer drivers have this as a print-time feature, and many PDF readers also have it as a print-time option before sending it to the printer.¹

* [CaSILE](https://github.com/sile-typesetter/casile) handles this already and can be asked to generate 2-up and booklet layouts for anything in has SILE render. You just append the request in the target filename. If you already generate an a5 pdf file with `casile make -- mybook-a5.pdf` then you can just ask for a booklet version on a paper double the size by `casile make -- mybook-a5-booklet.pdf` or do a 2-UP preview print on a4 by `casile make -- mybook-a5-2up.pdf`. Behind the scenes it is using `pdfbook2` for the booklet and a combination of `pdftk` and `pdfjam` for the 2up layout: https://github.com/sile-typesetter/casile/blob/master/rules/rules.mk#L487-L499. Hopefully these give you some idea to to achieve this effect with your own documents.
