### ISSUE TITLE
Multiple package initialization case?

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1531]
The same package can be (re)initialized multiple times (i.e. re-instantiated in `class:loadPackage`), e.g. infonodes gets initialized 2 or 3 times in the manual, notably leading to `Attempted to set the same function hook twice` warnings very early when processing the manual).

[Here](https://github.com/sile-typesetter/sile/blob/01be7155ab07057a51a80e82c07665cbfe268e95/classes/base.lua#L144), it seems to me that each time a package loads another one on which it is dependent, with `self.class:loadPackage()`, then a new instance is created.

_Originally posted by @Omikhleia in https://github.com/sile-typesetter/sile/issues/1366#issuecomment-1200265306_

**Comment by alerque** [comment]
Yes. In most cases I can think of this is probably just something we can skip. If the package is already loaded and the user asks to load it again just move on.

I can see a case some packages needing to be re-initialized though. For example the ones that accept *options* might want to do something else like throw an error or warning directing users to run a reconfigure command instead. Crop-marks for example might error if initialized more than once.

Should we have a "this package only needs to be initialized once, ignore multiples" flag? Or try to make all the `_init()` functions idemptotent and error on the ones that can't be? Or what?

**Comment by alerque** [comment]
I'm had a look at this and am having trouble coming up with a case that matters. The warning seems pretty noisy and not really relevant. Potentially I could see a use case for unsetting the old hook and resetting it again because this would change the order, but it would be a *last loaded* priority, and I think the *first time* a package gets loaded it is more likely to be in the right hook order with relevant packages.

I'm inclined to just silence the warning since it doesn't seem to be causing harm. This isn't about package init, it is about *hook functions* and since the function signature will only be the same if it is the exact same function there is little to worry about just leaving it. The rest of the `package:_init()` might have other issues, but this hook is the easies one to manage.

**Comment by Omikhleia** [comment]
Er nope, I think their are other cases that matter, for packages that override commands from other packages...

**Comment by Omikhleia** [comment]
Package A loads package B in its init and overrides command `b1`
Package C loads package B in its init and overrides command `b2`
Class loads package A, then C. Each time a new instance is created, i.e. commands are re-declared.

**Comment by alerque** [comment]
So? I don't see what's blocking that use case now. The warning is not coming from re-instantiating packages, it was coming from adding the same function (not the same function name, the exact same Lua closure signature) in the same hook queue.

**Comment by Omikhleia** [comment]
> Package A loads package B in its init and overrides command b1
Package C loads package B in its init and overrides command b2
Class loads package A, then C. Each time a new instance is created, i.e. commands are re-declared.

I think the user then has command b2 as modified by C, but original command b1. Am I wrong in my analysis?

**Comment by alerque** [comment]
> > Package A loads package B in its init and overrides command b1
> > Package C loads package B in its init and overrides command b2
> > Class loads package A, then C. Each time a new instance is created, i.e. commands are re-declared.
> 
> I think the user then has command b2 as modified by C, but original command b1. Am I wrong in my analysis?

Yes, but that's isn't even the same topic as the warning that prompted this issue. The warning is about class hooks not package inits.

If you want the b1 as modified by A **and** b2 as modified by C, then either C needs to notice the package is already initialized and not do so, just overriding b2, or the user should stash b1 after loading A but before C, then restore it afterwards.

**Comment by Omikhleia** [comment]
The issue was about effects of multiple package initialization case upon `self.class:loadPackage()`, with one immediate visible thing on hooks. C may not even know A exists and the user might load it with `\use`. But you seem you have eaten lions, so I am not going to argue further whether a package, loaded _after_ another package it might not even know overrode a command, should reset all overrides... Seems wrong or impossible to fix in an easy way, to me, but heh.

**Comment by alerque** [comment]
For the most part I would expect loading packages to be an idempotent operation. If the constructor (`:_init()` takes options, I would expect whatever was setup by earlier instantiations to be blown away by later ones but be equivalent if re-initialized with the same options.

I made a lot of progress to that end already in overhauling packages, and the hook warning was superfluous because it was being thrown on an operation expected to be idempotent.

If a package is overriding functions from another package, I would expect whoever is loading it to know what it does and act accordingly. Hence if a user loads A and C that are closely related I would expect them to realize they may loose some of A. If A and C are so unrelated from B that the user wouldn't expect B to be messed with, then **it shouldn't mess with B**. Perhaps at most it should wrap them or check for previous instantiations. Alternatively it might make sense for both A and C to *inherit* from B but only surface their modifications and do so under their own package namespace. This wouldn't affect command registrations which are currently global though, see #1510 for that. 

More to the point though, I suspect there are better ways to implement that A/B/C layout it the first place. If you have a real world example to go on this might make a lot more sense.

**Comment by alerque** [comment]
I've run into a case I had to get aggressive in hacking around not having an unload. I subclassed a book class for a special case build, but it was important it didn't try to write a TOC data file. Just assigning a noop function to the `:writeToc()` method was not enough because the hook was already set so it just called the old function closure. I was able to unset the hook, but we need a more ergonomic way to do that.

We have most of the information so we should be able to plumb this up from the base package.

**Comment by Omikhleia** [comment]
Use case 1:
- My master file loads package `printoptions` (amongs other) and includes user-contributed content (chapters). The former redefines `\svg` to add extra functionality to it.
- User A has `\use[module=packages.svg]` as he used it, and tested his file outside of my main class and the in-progress master file - Say he just used the plain class.
- Currently, this _re-instantiates_ the "svg" package, re-declaring commands, such killing my override.
- Am I going, now, to need "grep -v" the `\use` from user user-contributed content? (and possibly "sort -u" them to add them in my master file? That would work... But, really?)

Use case 2 (the real thing IMHO):
- Package "footnotes" loads "insertions" as a [depency](https://github.com/sile-typesetter/sile/blob/2afb5fa9500daef01f2e4d6229eb04d47f91a2ca/packages/footnotes/init.lua#L10)
- My own package "sidenodes" does it too. It does the exact same type of things than "footnote" but with different commands and default styling, and ideally acting on other frames, with additional tricky behavior on page changes (you may soon see some issue on "insertions", esp. regarding the undocumented "steal-position"... Not sure yet, but I'm chasing a bug, whether due to in my own use of it or not...). Anyhow, it may be used without footnotes being loaded (before/after it? I've no idea!), if users want sidenotes only; but could also work with it (if users want both, why not. The frames are there for users to use them, would they want, in my master templates...).
- So if they load both, "insertions" gets instantiated twice (currently), and it registers a typesetter [hook](https://github.com/sile-typesetter/sile/blob/2afb5fa9500daef01f2e4d6229eb04d47f91a2ca/packages/insertions/init.lua#L429) twice.
- Currently again, the latter does not ignores the second registrations (as, e.g. the class hook registrations do). Should it do it, with a warning - Er. without warning, as for the class hooks, since _this is going to happen_...

I dunno. I do feel something is currently broken, and that adding checks and hiding warnings is not the proper way (yet). All I can say is that is makes my task harder - Be it because broken behavior or unclear documentation, but all of this wasn't needed or wasn't a pain point in 0.12. The "hooks" introduce since then are cool, don't misunderstand me here. There current usage, with unexpected multiple package instantiations, isn't cool at all.

**Comment by alerque** [comment]
Every time I review this discussion I come up with more arguments *both* directions here. The loader being idempotent makes *tons* of sense to guarantee the state after running the function, but it does make it frustrating figuring out where to place an override.

It finally occurred to me today that we can do both. In #1908 I changed `:loadpackage()` to only run command and setting registrations once by default, but `:reloadpackage()` can be used to force them to run again if clobbering everything to get a known state is what you are after.

It works for a couple cases I tested on but could maybe use more work before release.

My though would be to make anything that takes the `options` run again, so setup commands would re-run if the loader was called again, but that the registration type functions would only run once.

Thoughts on having cake and eating it too?
