### ISSUE TITLE
Switching master on page change became weird?

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1544]
Use case: having a first page with a certain layout, and subsequent pages using another.

I cannot make any sense of the following changes between 0.12.5 and 0.14.2.

0.12.5 worked pretty easily:
```lua
omicv.newPage = function (self)
  if SILE.scratch.counters.folio.value > 1 then
    self.switchMaster("next")
  end
  return plain.newPage(self)
end
```
0.14.2 after much attempts, this does _seem_ to work:
```lua
function class:newPage ()
  plain:newPage() -- It calls and returns self:initialFrame(), but heh...
  self:switchMaster("next")
  return self:initialFrame() -- now this...
end
```

Not sure such weird things were expected and how one is supposed to effectively achieve that, but the "new" code above is real weird (while it looked obvious when I did it in 0.12)

EDIT: And the new code ditched the folio numbering test, because the folio is not even incremented _yet_ there...

**Comment by alerque** [comment]
I ran into some bug that might be the same one with a project on Saturday. I think I might have cross wired which hook is used in which package (masters & twoside). One one package using typesetter hooks the other class page hooks.

**Comment by alerque** [comment]
I think your issue and mind are different.

Yours I suspect is a race condition because the master stuff is getting setup before folios are initialized.

Both might still be connected because I think `:switchMaster()` is getting called too early in some/many/all cases.

**Comment by alerque** [comment]
If your use case is to use one master for one page and a different one for every other page in the document, why `:switchMaster()` on every page? Why not just set the master you use most of the time as the default, but on your one unique page use `:switchMasterOnePage()`? If that isn't desired at least just set the new master on page 2 and leave it after that. Switching it on every page doesn't seem right for this use case? (I say that having just chased down the fact that I was switching too many times myself and hence ending up on the wrong mirror side later in a document.)

**Comment by alerque** [comment]
I don't understand why you are trying to *both* inherit from `base:newPage()` *and* re-arrange the order. There is a hook in the middle of the function for exactly the purpose of injecting something in that location without having to replace the function. If you use inheritance you have no choice but to either do things before or after the parent function, not in the middle.

I would suggest either just completely replacing it with a modified function (i.e. not calling the parent class's original function at all) or using the `newpage` hook to do your switch or my previous suggestion of changing your default master.

Option A:

```lua
function class:newPage ()
  SILE.outputter:newPage()
  self:switchMaster("next")
  self:runHooks("newpage")
  return self:initialFrame()
end
```

Option B:

```lua
local first = true

local function pickmaster (class)
	if first then
		class:switchMaster("next")
		first = false
	end
end

function class:_init ()
   -- ...
	self:registerHook("newpage", pickmaster)
   -- ...
end
```

Option C:

Set your "next" master as the default for the class, then use the other one on the first page:

```lua
function class:_init ()
   -- load up masters package and set masters
   -- ...
   self:switchMasterOnePage("firstpagemaster")
   -- ...
end
```

I will note that the `:newPage()` name is confusing since it does not get run the first page. It is expected to close a page and open a new one, not just open a new one. Hence it probably should have been called `:nextPage()` or `:switchPage()` or something. Conveniently we can pass the blame on that one :wink:. If we did come up with a better name we agree on it would be easy enough to rename and shim the old name.

Feel free to re-open if none of that makes sense or doesn't answer your use case.
