### ISSUE TITLE
MathML msqrt not supported

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1604]
SILE 0.14.4

Document:
```
<document>
<use module="packages.math"/>

<mathml display="block"><mfrac><mrow><mo>−</mo><mi>b</mi><mo>±</mo><msqrt><mrow><mi mathvariant="normal">Δ</mi></mrow></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></mathml>

</document>
```

(I am not MathML-savvy, the MathML formula was generated with [TEMML](https://temml.org/) from LaTeX ` \frac{-b + \sqrt {\Delta}}{2a}`)

Expected:

![image](https://user-images.githubusercontent.com/18075640/201517768-1a3fcad8-6fbd-49f8-94b8-8a2f3da7626e.png)

Observed:
```
! Unknown math command msqrt at xmath.xml:50:1: in \mathml["display",display="block"]
```

**Comment by Omikhleia** [comment]
Actually, switching to the TeX-like **math** does produce some result:

```
\begin{document}
\use[module=packages.math]

\begin{math}
\frac{-b + \sqrt {\Delta}}{2a}
\end{math}

\end{document}
```

![image](https://user-images.githubusercontent.com/18075640/201518475-c527fab9-e9fc-4e73-88f0-ef92ef244633.png)

But the square root doesn't expand over the content.

**Comment by alerque** [comment]
@OlivierNicole No pressure to fix this, I'll totally understand if you don't have the bandwidth. But perhaps you could at least drop a pointer for what somebody needs to look into if they want to tackle this.

**Comment by OlivierNicole** [comment]
Indeed, square roots are not yet implemented. What you see when doing `\sqrt` in TeX-like mode is just the Unicode glyph for square roots.

Typesetting square roots is not entirely trivial because it’s a vertically stretchable glyph (see https://github.com/sile-typesetter/sile/issues/220#issuecomment-924395606). No theoretical difficulties there, just implementation time

Alas I cannot commit on starting working on this seriously anytime soon.

**Comment by Omikhleia** [comment]
The above XML MathML test script with PR #2119:

![image](https://github.com/user-attachments/assets/114ef331-13da-40ec-b64a-7ed49539fe62)
