### ISSUE TITLE
Multiple math package init breaks mu unit

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1607]
SILE 0.14.4

Multiple math package initialization (#1531) can cause math "mu" to break (generating an error when lengths in that unit are later "absolutized").

**Scenario**
- Both packages A and B can be used independently
- Both packages A and B load the math package as they are going to use it programmaticaly
- User document loads both packages... and then errors deep at math shaping.

**Workaround hack**

![image](https://user-images.githubusercontent.com/18075640/201555087-3fc6c804-bdca-4389-bc90-42586cd4bfc9.png)

**Analysis**
- Units converters are created on new index only (`setmetatable(units, { __newindex ....}` in `core/units.lua`)
- Upon multiple package re-instantiation, the _existing_ unit gets redefined, and the redefinition of the unit removes the converter so we are left with the definition only...
- Then upon actual use, an error occurs on that line:
  ![image](https://user-images.githubusercontent.com/18075640/201556061-74bf0441-38bd-4fcd-8325-16e3ea19eade.png)
- `def.converter` is nil (due to the redefinition override) but `def.value` is nil too (obviously, this is a relative unit...)

**Comments**

- Another case where package multiple instantiation can cause havoc (and long debugging sessions...)
- However the maintainers decide to stick to that weird concept... Any redefinition of units will break things.
- The above workaround works but has a bad code smell.
- While still code smell, that "protection check" could have been done in the old `SILE.registerUnit`, but it seems this function is pending deprecation (well, despite the small, it's getting tasty: the deprecation code is commented out...)

**Comment by alerque** [comment]
I don't think we can *properly* fix this until we have an *unloader* so that we can undo the effects of loading a module rather than just overriding it. We could check and just skip module reloads, but that wouldn't play nice with the module loader being able to pass the initialization options like it does now. An unload callback that reverses everything done is still in order I think.

In the mean time the case with units is relatively easy to fix and allowing them to be redefined with a new definition (rather than just incidentally setting the same things twice) is a possible use case, so I've just posted a PR that takes care of that.

**Comment by Omikhleia** [comment]
> We could check and just skip module reloads, but that wouldn't play nice with the module loader being able to pass the initialization options like it does now.

There a very few uses cases it for it, though.
