### ISSUE TITLE
Color at page break affects folios and other frames

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1659]
SILE 0.14.5

If some colored text is split at page boundary, the color also affects the folio number and other frames (e.g. footnotes)

MWE:

![image](https://user-images.githubusercontent.com/18075640/207994113-aae33dfc-e42d-475a-bd0d-1a4e35ff3eb5.png)

```
\begin[papersize=a8,class=book]{document}
\use[module=packages.color]
\font[size=14pt]

Lorem ipsum dolor sit amet some random raw text for example.

Lorem ipsum.

Lorem ipsum dolor\footnote{Note} sit amet some random raw \color[color=red]{text for example of color lorem ipsum}.
\end{document}
```

(The critical apparatus I am typesetting contains "unclear" parts and "emendations", I was considering using colors for them, e.g. a light gray for unclear words and some dark gray for emendations - But I wouldn't have expected the color to span over the folios, footnotes, margins, etc. if the colored part of a sentence happens to be page-broken.)

**Comment by alerque** [comment]
Interesting problem. I guess we need a color push/pop in the frame break hook eh?

**Comment by alerque** [comment]
Hmm. This is somewhat messier than I first imagined. We can't just add a frame enter/leave hook that pushes/pops the default color because all we're going to end up with is the footnote and folio frames popping back to the (wrong) color. We can't add a hook that only works on the current frame ID because the next frame may or may not have the same ID.

I think the right answer is probably that we need a hook to run whenever we switch typesetters, or a way to stuff information like the current color into the typesetter state and then make sure the backend updates it as necessary.
