### ISSUE TITLE
SILE 0.14.6 breaks packages using defaultTypesetter

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1660]
The `defaultTypesetter` was removed in 0.14.6 via 6bb02d558e551898513cadc3225420f4bf49f423

This is somewhat of a breaking change for some 3rd-party packages.

Also, it is still mentioned in the documentation, e.g.
https://github.com/sile-typesetter/sile/blob/e3ca9529da3941b2d6bb125b5a188f65fc47e7a4/documentation/c12-tricks.sil#L47

(And the doc still used the old object syntax by the way)

**Comment by Omikhleia** [comment]
Apparently the trick is just to replace `SILE.defaultTypesetter()` with `SILE.typesetters.base()` (with or without frame argument) - Could be mentioned in the release notes.

**Comment by alerque** [comment]
I thought there was as shim in place already for `defaultTypesetter` to warn and redirect to `typesetters.base`, but apparently I didn't test the legacy use cases. It should be possible to add back a shim that throws a relevant warning on legacy usage.

**Comment by Omikhleia** [comment]
> It should be possible to add back a shim that throws a relevant warning on legacy usage.

Bah, do we really need? I fixed my case, and I am not that sure there are many package writers in activity :eyes: 

But we need to remember fixing the manual (and testing these "diglot" examples perhaps? On my side, I have just browsed that part (c12) for concepts and ideas, but never really tried to reproduce the examples.

**Comment by alerque** [comment]
I'll put the shim in for my own sake if nothing else, I have a bunch of old projects that are bound to bump into it and the reminder saves debug time someday when I need to upgrade something.

I figured out what slipped ... I though the deprecation shim was already in place but it turns out what I had dealt with was the move from `core.typesetter` to `typesetters.base`, but that module name change was done back in v0.14.0 without also addressing the `SILE.defaultTypesetter` global that was being instantiated in a module not matching the namespace. Now that I the code in `typesetters.base` actually returns just a class without monkeying with globals we just need to fire up a `defaultTypesetter` in our deprecations file and throw a warning on access.

**Comment by alerque** [comment]
c12 docs need a complete overhaul, the examples are way behind.

**Comment by alerque** [comment]
I started taking a swing at this. The shim should be easy, the docs are a bit more work...

**Comment by alerque** [comment]
A caveat with the shim that will go in place for this: There are two possible use cases and only one of them is feasible to shim.

1. One use case is instantiating a typesetter. The old way was `typesetter = SILE.defaultTypesetter {}` and is easily shimed to `typesetter = SILE.typesetters.base(frame)`. Once instantiated basically all further usage is unchanged.
2. The other use case was for monkeying with the existing methods of the defaultTypesetter. This turns out to be very difficult to shim so I am just leaving it as-is. Patching an instantiated typesetter still works, but patching the default one should be a job for code that has actually been updated to use the current API pattern. There are too many ways it could have been monkeyed with to shim.

As a note for anybody getting hit by the second use case, the expected usage now is NOT to change the default typesetter class at all but to create a new class using the default base class as a starting point, then override any methods desired, then instantiate typesetters using the new class.
