### ISSUE TITLE
Regression with SILE.processString

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1674]
```
\begin{document}
\script{
    SILE.processString("For instance, this \\em{entire} sentence is typeset in a \\em{raw block}, in SILE language", "sil")
}
\end{document}
```

- Worked with SILE 0.14.4
- Errors in SILE v0.14.6.r8-g771d87f
```
SILE v0.14.6.r8-g771d87f-dirty (Lua 5.4)
<experiments/pstring.sil> as sil
<./core/sile.lua:391> as lua
<[string "..."]:2> as sil

! Document has more than one parent node that looks like a master document! at [string "..."]:2: in <snippet>:
		[[For instance, this \em{entire} sentence is typeset in a \em{raw block}, in SILE language]] near experiments/pstring.sil:2:1: in \script
```

- A possible "workaround" is to wrap the raw string in a `\document{` ... `}`, but I wonder whether this was expected...

**Comment by alerque** [comment]
No this is not expected, per memory the `processString()` function was expected to cope with document fragments like `doTexLike()` used to do.

**Comment by alerque** [comment]
So it turns out there are more scenarios here than I ever had in mind. So far we had covered (and recovered) the case of a top level document, then we added the ability to discard cruft like comments outside of a top level document without killing the parser. We also had a way to handle fragments. The case we didn't cover was fragments that had more than one top level tag. A simple fragment like `\foo{bar}` or `foo bar` was working fine, but a fragment like `foo \foo{bar}` suddenly has two top level nodes.

I think tho new PR should cover that case as well at the expense (possible breaking change for some scenarios if you are processing the raw AST) of a new top level document node being returned to wrap fragments (but not documents).
