### ISSUE TITLE
Minor missing type coercion for some boolean options

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1689]
Fairly minor, but:

The (undocumented) option `discardable` on the `\skip`  command cannot be used properly from a SILE document (and needs to be a true boolean if used from Lua).

```
\skip[height=5pt, discardable=true]% seems to work, because "true" as string is truthy...
\skip[height=5pt, discardable=false]% but now doesn't do what one would expect!
```

It would need to be coerced to boolean:

https://github.com/sile-typesetter/sile/blob/13df3c1f56ea5e68067b4ce00efc198b07de857c/classes/base.lua#L461

Suggested fix:
```lua
    options.discardable = SU.boolean(options.discardable, false)
```

Likewise in the same file:

https://github.com/sile-typesetter/sile/blob/13df3c1f56ea5e68067b4ce00efc198b07de857c/classes/base.lua#L420

Suggested fix:
```lua
    if SU.boolean(options.vertical, false) and not SILE.typesetter:vmode() then
```

**Comment by alerque** [comment]
Correct, all values coming from parsed content need to be coerced to the expected types. This is only noticeable when automatic conversion doesn't work (e.g. when string "false" coerces to boolean True) but should be considered a code bug in all instances. Also for strings they should be cast to lengths or other types using `SU.cast("lengths", value)` or similar using our utility functions. There are probably quite a few of these types of bugs since we are not able to lint for them yet nor do we have any support for type checks (c.f #871).
