### ISSUE TITLE
sile-0.14.8.zip from Jan 26 missing smiley.svg

### ISSUE THREAD

**Issue by watchtmouse** [sile-typesetter/sile#1746]
Thanks for the SILE package.

Been following for a while, this is my first serious attempt to do something real with SILE.
Please note that this is my first ever issue submitted for this (github) Platform.

This is a hint for others running into the same issue.

I think this is a packaging issue.
When this is not the proper way to report these kind of issues please, tell me so and close the issue.

After unpacking the zip and building like:
`cd ~/sile-0.14.8`
`./configure`
`make`

running
`./sile documentation/sile.sil`

gives me 
... (indicating many lines with "normal" warnings)
`[62] [63] <./packages/autodoc/init.lua:163> as sil`
`<./packages/autodoc/init.lua:163> as sil`

`! Unable to find file 'packages/svg/smiley.svg':`
`	no file 'packages/svg/smiley.svg'`
`	no file 'documentation/packages/svg/smiley.svg' at ./packages/autodoc/init.lua:163:9:1: in` `\svg[height="12pt",src="packages/svg/smiley.svg"]`

`! Couldn't find file packages/svg/smiley.svg at ./packages/autodoc/init.lua:163:9:1: in` `\svg[height="12pt",src="packages/svg/smiley.svg"]`

`error summary:`
`	Processing at: ./packages/autodoc/init.lua:163:9:1: in \svg[height="12pt",src="packages/svg/smiley.svg"]`
`	Using code at: ./packages/svg/init.lua:56: Couldn't find file packages/svg/smiley.svg`

`Run with --traceback for more detailed trace leading up to errors.`

I was able to correct and create the complete sile.pdf with,
`cd ~/sile-0.14.8/`
`mkdir -p documentation/packages/svg`
`cd documentation/packages/svg`
`wget https://github.com/sile-typesetter/sile/blob/master/packages/svg/smiley.svg`
`cd ~/sile-0.14.8/`

and re-running
`./sile documentation/sile.sil`

**Comment by alerque** [comment]
Thanks for the report. The file is used in making the docs and not included in the source distribution. I'll fix that.

In the mean time if you actually want to *hack on* SILE or do anything other than compile, install, and move on then I recommend using a Git clone instead of the source release.

**Comment by alerque** [comment]
> and re-running
> `./sile documentation/sile.sil`

Just an FYI, this will not work to build the manual properly. The manual depends on many specific fonts and versions.

You can use `make docs` to regenerate the manual which will also download the necessary fonts and also do things like make sure the TOC is fully generated (2 runs).

**Comment by watchtmouse** [comment]
Thanks for quick response and the tip on make docs command,

I did check the (./sile documentation/sile.sil) build report about missing fonts, and downloaded these manually.
the make docs command will make this much simpler, thanks for providing this.

at the moment for me
`make docs`
reports
`make: Nothing to be done for 'docs'.`

I also did the second run to incorporate the generated TOC file
so all seems fine.

**Comment by alerque** [comment]
In general `make` only looks at timestamps to figure out if there is anything to be done, it doesn't have any way to confirm if anything was done right. Since you built it manually it will think it's done. You can use `-B` to override that and force it to build anyway, so `make docs -B` will start from scratch and build everything needed up to the docs.

Also note there are special configure flags related to this, `./configure --with-manual` will configure the sources to think a manual needs to be built at all. This is the default for the source package, but a prebuilt and up to date manual is also included in the source package so it usually doesn't actually run the `docs` target when running `make`. Also a `./configure --enable-developer` flag at configure time will add several make targets and some extra dependencies for tooling used during the development cycle, like the tooling needed to run the test suite.
