### ISSUE TITLE
Equation numbering in display math

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1800]
In TeX-math in display math, one can add an equation number with `\eqno(xxx)`, that gets pushed to the end of the line:
![image](https://user-images.githubusercontent.com/18075640/236795934-b474125e-5142-46d1-923e-8e82e529dca5.png)

We don't seem to have such a thing.
My workaround here is to use `\,{\quad(xxx)}` -- the extra bracked are here for the parenthesis not to adapt to the rest of the formula, and the thin space to avoid issues depending on previous content... E.g. `\frac[a}{b} {\quad(xx)}` raises an issue about trying to use `\frac` with more than 2 arguments... Besides being contrived, it doesn't show very nicely.

**Comment by leorosa** [comment]
To have aligned numbers, another workaround would be to use something like this:
`\hfill \begin[mode=text]{math} .... \end{math} \hfill (xx)`
But, in this way the equations appearance is not the desired one.

I took the liberty to change the math package, in order to add a third mode, in wich equations are shown in the display mode, including a counter. Please see https://github.com/sile-typesetter/sile/pull/1821

**Comment by Omikhleia** [comment]
Display math equation numbering was addressed in #2020 (my re-adaptation of @leorosa 's initial attempt), and released with **0.15.0** = We do have a solution now, so closing the issue.
