### ISSUE TITLE
Busted tests broken by ICU 73

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#1831]
ICU 73 is causing different localized number formatting output for Russian and Arabic as opposed to 72 and prior. This has broken our tests, specifically the Busted unit tests for the number format utility function. It isn't showing up in CI yet because Ubuntu runs a bit behind the times.

**Comment by Omikhleia** [comment]
For the record or future need in case of questions:
This is apparently from https://unicode-org.atlassian.net/browse/CLDR-16089
= reported fixed in CDLR 43 (and [ICU 73.x](https://icu.unicode.org/download/73) indeed updates to CDLR 43.x)

Following impacts are listed (so with other changes than just Arabic and Russian)

lang | impact|
----- | ---------- |
ar | No fallback, remove the dot "." |  
el | No fallback, remove the dot "." |  
en_IN | No fallback, remove the dot "." |  
he | No fallback, remove the dot "." |  
nl | Replace "." by "e" | 125e workout
pl | No fallback, remove the dot "." |  
ru | No fallback, remove the dot "." |
uk | No fallback, remove the dot "."|

</span></span>
