### ISSUE TITLE
Typesetting sile.sil with the Docker image

### ISSUE THREAD

**Issue by AKielhorn** [sile-typesetter/sile#1855]
Since I have SILE 0.14.11 working from the docker image, I tried to build the documentation.

First problem:

`sile.sil` includes files with `\include[src=documentation/...]` but the files are at the same level.
Moving `sile.sil` one level up solved the problem.

Second problem:

`sile.sil` needs lots of fonts. Downloading the fonts was no problem, since the `Makefile-fonts` tells me where to download the files. (Except for Noto CJK, It seems a lot has changed there.)
But I still don't know why I had to install `Cormorant Infant` since there was no reference in the manual.

(It is used in `init.lua` for `autodoc:example` but that was a surprise.)

Third problem:

```
! Unable to find file 'packages/svg/smiley.svg': no file 'packages/svg/smiley.svg' at /usr/local/share/sile/packages/autodoc/init.lua:166:9:1: in \svg[height="12pt",src="packages/svg/smiley.svg"]

! Couldn't find file packages/svg/smiley.svg at /usr/local/share/sile/packages/autodoc/init.lua:166:9:1: in \svg[height="12pt",src="packages/svg/smiley.svg"]

error summary:
	Processing at: /usr/local/share/sile/packages/autodoc/init.lua:166:9:1: in \svg[height="12pt",src="packages/svg/smiley.svg"]
	Using code at: /usr/local/share/sile/packages/svg/init.lua:56: Couldn't find file packages/svg/smiley.svg
```

The file `packages/svg/smiley.svg` exists, but it seems that the search path is wrong.

When I look into `image.lua` it uses `\autodoc:command{\img[src=documentation/gutenberg.png]}` which works.

That gives me an idea:

If I put `packages/svg/smiley.svg` into the CWD it should work and indeed it does.

Fourth problem:

Turning a `.dot` file into a `.pdf` file. Well, that's what `Graphviz` ist for.

Now I have 125 pages of documentation and you won't hear from me in a while:-)

**Comment by Omikhleia** [comment]
Regarding Cormorant Infant: We wanted examples typeset in a different font (at one point this was in the manual, and this was eventually moved to the autodoc package, not why it would be an issue?).

**Comment by alerque** [comment]
Most SILE users are *not* expected to render their own copy of the manual. The finished product is a decent example of what can be done, but it has *MANY* expectations about the available resources that are not things we expect of most users. We do kind of expect it of SILE developers, although since the manual is generated in CI it is possible to contribute without setting up your local system with all the requirements.

* Since we don't expect people to build it, we do post copies of the PDF on our website, attach them to every release, and even include pre-rendered PDFs in the source distribution tarball. Only if you are working with a Git clone of this repository do you not have a prebuilt one sitting around. You can download one though from the releases section here on GH or from our site.
* If you plan to build your own manual, the Docker version isn't the way to go. It can be made to work, but you have to make sure to mount the whole SILE project directory as a volume inside the Docker container, not just the documentation directory. It is not meant to stand on it's own apart from the rest of the sources.
* If you use the Docker image to build the manual you'll need to take care of font downloads and such on your own.
* A much easier way is to just use the SILE sources directly and build your own SILE. Part of the configure process is an optional `./configure --with-manual` that will make sure your system is setup with the right tools needed to build the manual, then when you do a `make` the manual will be generated too. It can be regenerated later with `make docs`. This will automatically fetch all the right fonts and such as well as generate the graphs and such referenced in the manual.

**Comment by alerque** [comment]
Happy to answer further questions or help with anything you're trying to accomplish. Only closing because I *think* that covers the bases here...
