### ISSUE TITLE
"table of contents has changed" always emitted

### ISSUE THREAD

**Issue by nawordar** [sile-typesetter/sile#1857]
There is already a #1732 issue, but in my case, even the simplest document with just one chapter emits that warning:

```tex
\begin[class=book, papersize=a4]{document}

\chapter{A Scandal In Bohemia}
To Sherlock Holmes she is always \em{the woman}.

\end{document}
```

```
$ sile test.sil
SILE v0.14.11 (Lua 5.4)
<test.sil> as sil
[1] [2] </usr/share/sile/core/languages.lua:75> as xml
[3] 
! Warning: table of contents has changed, please rerun SILE to update it.

$ sile test.sil
SILE v0.14.11 (Lua 5.4)
<test.sil> as sil
[1] [2] </usr/share/sile/core/languages.lua:75> as xml
[3] 
! Warning: table of contents has changed, please rerun SILE to update it.
```

Rerunning doesn't do anything. The `test.toc` file always has the same content:

```lua
return {
  {
    label = {
      "A Scandal In Bohemia",
      id = "stuff"
    },
    level = 1,
    number = "1",
    pageno = "3"
  }
}
```

OS: Arch Linux
SILE version: 0.14.11 (Lua 5.4)

**Comment by alerque** [comment]
Thanks for the report. This useless message is happening because the *existing* TOC file data is not even being read/loaded if a TOC is not output, so comparing an empty table to a full table comes up "changed" every time. I set it up to skip the test if the TOC content wasn't loaded and used and hence its freshness is of no concern to the user anyway.
