### ISSUE TITLE
Class instance check weirdness

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1861]
For feature detection in a package, I wanted to check whether the current class is some specific class (or derived), to take some specific actions.

I encountered a weird issue and extracted a MWE:

```
\begin[papersize=a5, class=book]{document}
\lua{
local class = SILE.documentState.documentClass
local plain = require("classes.plain")
local book = require("classes.book")
print("Derives from plain:", class:is_a(plain)) -- true
print("Derives from book:", class:is_a(book)) -- false! EEK?

-- Penlight works well basically
local Cat = pl.class({})
local Lion = pl.class(Cat)
local instance = Lion()
print("A lion derives from Cat:", instance:is_a(Cat)) -- true
print("A lion derives from Lion:", instance:is_a(Lion)) -- true
}
\end{document}
```

It turns out that the document class is loaded with a `SILE.require`:

https://github.com/sile-typesetter/sile/blob/848920b754ce24003fbf771eb88695ddf1aa7e91/inputters/base.lua#L27

And the latter performs a path operation:

https://github.com/sile-typesetter/sile/blob/848920b754ce24003fbf771eb88695ddf1aa7e91/core/sile.lua#L203

If I change that SILE line to `status, lib = pcall(require, pathprefix .. "." .. dependency)`, or reciprocally my own code above to `local book = require("classes/book")`, then the `class:is_a(book)` now works as expected and returns true.

Which is the correct fix?

**Comment by alerque** [comment]
Good grief. I suspect this is going to teach me something about Lua VMs I didn't know before this issue. Why is the meta table different depending on the path? And most pressingly why is exactly the *opposite* fix true for `classes.plain` vs. `classes.book`?

**Comment by alerque** [comment]
So Lua is isolating tables in closures using the key in `package.loaded`. There is no difference between `classes.plain` and `classes.book` except which one got loaded *first*—that's the one that gets loaded with `SILE.require()`. The use of `pl.path.…` is bogus here because it is not a path, it is a module spec. We've been encouraging actual Lua module specs everywhere and Lua adapts `.` to the platform's path separator anyway. As such we should be concatenating using `.`.
