### ISSUE TITLE
! No localized message for tableofcontents-title found in locale en...

### ISSUE THREAD

**Issue by jodros** [sile-typesetter/sile#1993]
Since I'm playing with this package for now, I just found that the fluent command is only working when the language is passed using `\language[main=]`...

```txt
\document[class=book]{
\tableofcontents
\chapter{I}
}
```

However this works

```txt
\document[class=book]{
\language[main=en]
\tableofcontents
\chapter{I}
}
```

Is it a bug or my own fault? If so, maybe it has something to do with the fact that `\language` calls `SILE.languageSupport.loadLanguage()`?

**Comment by Omikhleia** [comment]
Rings bell. Maybe it's the same bug as #1157?

**Comment by alerque** [comment]
Yes this is the same as #1157. And it's somewhat embarrassing that hasn't been decided on and fixed. I know *why* ... because my own work (and particularly 100% of book projects that would have a ToC) depend on CaSILE which does set a default language even if projects don't call one out, so I never hit this bug.

But we should decide which path ... "en" or "und" by default? Comments welcome on the original issue.
