### ISSUE TITLE
BSD version too old.

### ISSUE THREAD

**Issue by jodros** [sile-typesetter/sile#2185]

**Comment by Omikhleia** [comment]
On the other hand, who cares? [BSD](https://w3techs.com/technologies/comparison/os-bsd,os-linux,os-windows) doesn't weight much the efforts, unless some BSD folks tackle with it.

**Comment by alerque** [comment]
Yup. It's pretty old indeed. And I'm aware of it, but it isn't this project's problem or mine either. Nobody involved here upstream actively uses BSD.

We do build and test every commit, PR, and release on Free BSD from source in CI, so we know it *can* work and indeed *does* work with an easy recipe to get the dependencies going. I've thought of dropping the mentions of it from our docs, but we do still regularly get inquires about it. I've personally directed several people how to get it building from sources.

The effort to keep CI working has been worth it because having everything working on `bmake` smoothes out the packaging for other platforms as well including macOS.

I assume the hold up is the current upstream maintainer doesn't have a current use for it and doesn't feel like packaging the additional Lua dependencies we added. Hopefully somebody comes along that *is* interested and can get it up to speed

In the mean time I don't think we need a tracking issue here since there isn't much more we can do on this side. Our CI already points the way to everything necessary for building on BSD, it is just a matter of some BSD folks actually doing it.
