### ISSUE TITLE
Package manager

### ISSUE THREAD

**Issue by suhr** [sile-typesetter/sile#324]
To install SILE packages somewhere into `$HOME/.sile/` (or `$HOME/.local/share/sile`). Also SILE should search for packages in that location.

PS: there's some useful [article](https://medium.com/@sdboyer/so-you-want-to-write-a-package-manager-4ae9c17d9527).

**Comment by alerque** [comment]
I agree sooner or later this is going to be necessary. But I also know implementing it is going to be painful, no matter how right we try to do it. Surely we can do better than TeX's CTAN or Lua's rocks, but it might take a couple iterations before we get something flexible and really useful.

Obviously  the biggest hassle is going to be versioning and the interaction between SILE versions, package versions, and documents. I've been putting together a library of things I use for various books and still can't get my head around what bits need to be versioned alongside the document and what bits can be independent. At the moment every upgrade to SILE means a good deal of manually checking, comparing, and usually a few tweaks to by code to interact nicely with upstream changes. Doing this for my own personal collection is enough of a mind bender, sorting it out to work for others is not going to be a  walk in the park.

**Comment by simoncozens** [comment]
You know what, right now, I'm thinking that all user-contributed packages and classes should just go in the SILE distribution. Avoids all the package manager madness, and we're talking about a bunch of tiny Lua files. Right now the packages and classes directories take up 300 kilobytes. If that grew by a factor of 100, I still wouldn't be worried.

**Comment by alerque** [comment]
I wouldn't be worried about the size either—and I even agree that right now the best solution for contributed packages is to just accept them as part of the upstream packages repo and version them along with SILE.

However that isn't the only problem here. The two issues I see that call for a separate package manager (eventually) are:

* Private packages that won't be contributed back upstream. I'm in this scenario already. I have a toolbox for our publishing house that has classes, functions and all sorts of gizmos that are specific to our projects. I'm keeping an eye on it and when I do things that would be useful to more than just us I try to refactor it as a package and contribute it to SILE, but not everything in there makes sense to push out to other people.

   Not having a package management system that SILE knows about leaves me a build system reminiscent of MacGyver's handiwork. It's serving me so far, but versioning is already an issue. Once a book is released it may or may not build the same with the next version of the toolkit, so I have it set as a versioned git submodule in each book or series repository and a Makefile that runs sile with the right paths set.

   This setup would hardly be intuitive to some green horn that comes along and wants to get started. An established package management system would give other publishing houses a path to follow rather than having to re-invent the wheel.

* Even if the size on disk is not an issue for contributed packages maintaining them will not be easy. As SILE behavior changes in future releases packages will need to be updated to behave correctly themselves. This is hardly overwhelming now, but with a lot more packages it will get harder and harder to come to a point where we can cut a release and expect everything tagged to Play Nice™.

**Comment by alerque** [comment]
For the record, the current package manager is entirely unusable for most of my use cases. Letting it run as root and write to my system's package manager managed file space is simply untenable for most systems. A home or project based path is something we have to add before I can even use it.

Additionally it's worth noting that Docker containers & most CI runners are going to have trouble accessing system paths as well. Something needs to be done that at least *can* be project or user local.

**Comment by simoncozens** [comment]
Fair enough. I also think we will probably end up going down the packages.lock route for document reproducibility.

**Comment by alerque** [comment]
Whether #538 is the answer to this, this has got to go. It does not play nice with distrubtion packages at all and leaves us with very little that *does*. The result are [hacks like this](https://github.com/Omikhleia/omikhleia-sile-packages/pull/6) that just try to cram everything into the SILE source.

**Comment by simoncozens** [comment]
Grr. Would writing to the user's home directory be more acceptable?

**Comment by alerque** [comment]
> Grr. Would writing to the user's home directory be more acceptable?

We're going to need an approach that works for several different use cases. Same problem most package managers end up with and have to solve for three different use cases:

* system
* user
* project

If any are left out it is typically the reverse of that order. First and at the very least solve for project level, second solve for user, third for system. Non-project systems (like editor / other app plugins) cat start at the user level with an optional system level.

I'm more and more convinced LuaRocks is going to be a significant ally here.

**Comment by alerque** [comment]
As of #1450 which will be released in v0.14.0, SILE now supports packages installed via LuaRocks. This is documented in the manual and discussed in related PRs, but here is a brief overview re this issue:

* SILE has always scanned the default Lua `package.path` for packages when asked to load one in addition to it's own installation directory. Now it also appends an extra `/sile` to the default Lua paths before scanning them. That means `SILE.require(packages.foo)` will look in all the usual Lua places for things that are SILE specific packages (e.g. `/usr/share/lua/5.4/sile/?/init.lua`).
* Package / class authors can create, publish, and install packages with the usual `luaarocks` tooling just by setting the module path in the rockspec to have SILE as the top level directory. This also allows 3rd party addons to override almost any core parts of SILE.
* This enabled at least 4 possible installation locations:
  1. System default (root usually required). These will automatically be used by all invocations of SILE.
  2. User directory installations (`luarocks --local install`). Use in SILE will require exporting the paths fires, e.g. with `eval $(luarocks --local path)`.
  3. Project local installations (`luarocks --tree ./ install`). Will work automatically when rendering documents in that directory.
  4. Any custom library location(s) you choose, use `--tree` with the path to each location you want to load. Requires adding to the standard Lua path like option №2 before use.

Rocks can be published on luarocks.org, but they can also be in private repositories with the standard tooling. In most cases a LuaRocks enabled SILE addon repository could also be added as a submodule to a SILE project or just extracted to the same directory for use without having to even touch LuaRocks.

**Comment by alerque** [comment]
> > The result are [hacks like this](https://github.com/Omikhleia/omikhleia-sile-packages/pull/6) that j
> > _alerque at [#324 (comment)](https://github.com/sile-typesetter/sile/issues/324#issuecomment-1011103512)_
> 
> hi! why pkgbuild are hacks? i was thinking that since msys2 also uses pacman, so, maybe pacman would be good for other such stuff too.

The use of a `PKGBUILD` to install an addon package is *not* by definition a hack. Of course that's something I'd like to see better supported (I am an Arch Linux TU and package hundreds of things both for official repos and the AUR).

The issue here is that *the specifics of the PKGBUILD needed in this case** have it reaching into a directory owned by another package and could easily create file conflicts down the road either between 3rd party packages or if SILE itself renames something the packages might break. Instead we should support an official place to put 3rd party stuff that isn't embeded in the SILE core package.

> secondly, the main concern i was having, regardless of what package manager is implemented, was that it would be nice to have some way to group the packages. and the obvious dependency resolution.

I don't know what you mean by grouping necessarily.

The solution we've come up with using LuaRocks handles dependency resolution.

It will also facilitate an easier/lessy hacky way to create a PKGBUILD that installs 3rd party bits.

> illustrating in context of latex, there are lots of softwares which "publish pdfs" in tex, and the latex packages used by one of the software are more or less defined. Like octave/matlab ; or the micromaths ; or the lyx ; or something else. So, being able to group packages like this would make package management and installing those much more simpler.

How is this different that just defining "x" to have dependencies on "a", "b", "c". etc. and installing "x".

**Comment by yashpalgoyal1304** [comment]
> I don't know what you mean by grouping necessarily.
> How is this different that just defining "x" to have dependencies on "a", "b", "c". etc. and installing "x".

How i think it to differ is that: a group "x" is not something itself, it's just a list... whereas a package "x" dependent on others, in something itself too, it's function depends on those, and it still can exists without its dependencies...

the concept of group i have thought before, but this term actually i took from `pacman` itself (src: [arch-wiki](https://wiki.archlinux.org/title/Pacman#Installing_package_groups))

```
pacman -S -g, --groups         view all members of a package group
                       (-gg to view all groups and members)
pacman -Q -g, --groups         view all members of a package group
```

**Comment by alerque** [comment]
I understand the concept of groups in the context of a system package manager. You could easily add a `group=()` field to your PKGBUILDs that install various addons, or just setup a PKGBUILD that is just a list of dependencies. The same could be done with a LuaRocks rockspec (making a more per-project-friendly way to specify a list of dependencies). Honestly it would be easier to reason about with a specific set in mind, in the abstract I'm not sure yet what a use case for this is that isn't actually just a list of dependencies.

What I don't understand is what, if anything, you think SILE itself has to do with "groups". The most likely match in SILE terms of a "group" is setting up a *class* that inherits from some other class and loads up a set of packages and potentially configures them in a certain way.
