### ISSUE TITLE
Escaping mechanism in tex-like input

### ISSUE THREAD

**Issue by gnodet** [sile-typesetter/sile#338]
We should be able to escape special characters `\%{}`, and also `"` inside quoted strings :

```
\script{
SILE.typesetter:typeset("\\\%\{\}\"")
}
```

**Comment by alerque** [comment]
I'm sorry I didn't realize there was an open issue about this or I would have commented sooner.

Let me break this down by the 5 characters that are problematic (because of their special meaning in TeXlike syntax):

1. `\` — This one already works fine:

    ```lua
    SILE.typesetter:typeset("\\") -- outputs a backslash
    ```

    This actually isn't representative of TeXlike syntax paring at all, this is a Lua string escape thing happening.

2. `%` — This doesn't need any escaping at all in this content. It has a meaning in TeXlike syntax, but the rules af that syntax are _mostly_ suspended inside Lua script code:

    ```lua
    SILE.typesetter:typeset("%") -- outputs a percent sign
    ```

3. `{` — Braces are tricky. They actually _don't_ need escaping at all, you can use them as they are. The trick is that you **must** balance them inside a script command. The `\script{...}` command will be closed by the first right curly brace nested at the same level as the one that opened it. In other words if you a `{` inside the script tag ANYWHERE you must also include a closing brace otherwise SILE won't be able to discern where the Lua code stops and TeXlike syntax begins again.

    If you want to output an unbalanced brace, include it's balance in a Lua comment:

    ```lua
    SILE.typesetter:typeset("{balanced}")
    SILE.typesetter:typeset("{left") -- }
    -- {
    SILE.typesetter:typeset("right}")
    ```

    There is another way to skin this cat too. You are using the simple `\script{...}` command form. If you switch to using the environment block form `\begin{script}...\end{script}` then all issues with balanced braces go away. The closing tag that SILE is looking for in this case is not the next balanced `}` but the next balanced `\end{script}`. That's a much easier thing to avoid, no?

    ```tex
    \begin{script}
    SILE.typesetter:typeset("{unbalanced") -- no problem
    \end{script}
    ```

4. `}` — see point 3.

5. `"` — This works already too. Remember what you are escaping here is not actually TeXlike syntax, this is a Lua escape and the contents of the *script* command is being passed through to Lua. As double quotes have no relevance to finding the start/end of a script, they aren't relevant here.

    ```lua
    SILE.typesetter:typeset("\"") -- outputs a double quote mark
    ```

    A related issue with double quotes in TeXlike syntax was recently fixed, see #940 that enables things like `\pullquote[start="\"",end="\""]{foo}`.

Some of these may not have worked in 2016 when you opened this, but most of this has been the case at least since last July or so when I got the Lua passthrough working properly.
