### ISSUE TITLE
Jagpdf 

### ISSUE THREAD

**Issue by lprndn** [sile-typesetter/sile#449]
Hi!
In my quest for ICC profiles in #444, I ended up searching for an alternative backend as it seems kind of compromised with libtexpdf.
I'm currently looking at jagpdf. The library is unmaintained so I'm trying to extract it libtexpdf style.
The thing is just that I found #10 , so I'm just wondering if @simoncozens have any information that might be useful?
Thanks,

**Comment by simoncozens** [comment]
I do remember looking at jagpdf but I'm afraid I don't remember why I didn't go that way. I did implement a podofo backend. It seems like it would be easy enough to implement.

But I wouldn't give up on libtexpdf yet. There's an `#if 0`'d function in `pdfcolor.c` called `pdf_colorspace_load_ICCBased` which seems to do what you want. It was only commented out because nothing in TeX/dvipdfmx used it.

**Comment by lprndn** [comment]
Ok thank you for the tip!
Actually, in libtexpdf, it's a comment in `pdfcolor.h` that worries me. It dramatically says `Not working` above `pdf_colorspace_load_ICCBased`. But I'll try to look into it.

**Comment by simoncozens** [comment]
I'll ask the TeX Live guys.

**Comment by Omikhleia** [comment]
Rejected (Wontfix): JagPDF is unmaintained for a long time.
