### ISSUE TITLE
! Font 'Gentium Plus' not available, falling back to 'Times'

### ISSUE THREAD

**Issue by clintolsen** [sile-typesetter/sile#467]
1) I see this message even if I've performed a font override.

2) On a Mac, even though it falls back to Times, something is up with the font rendering (I think this may be a .dfont type), and I get box outlines again.

**Comment by simoncozens** [comment]
Can you show me a brief example input file? I suspect it's something like, you've overridden the font for the conte frame but the page number is still coming out in the default font. (Hmm. Maybe we should provide a way of overriding the default font for the whole document.)

And yes, the dfont problem on Mac is well known. Do you have Gentium Plus installed?

**Comment by clintolsen** [comment]
I took your letter.sil (from github since I don't think brew installs tests?):

<pre>\begin[papersize=a5,class=letter]{document}
\font[family=Latin Modern Roman,size=11pt]
\recipient{John Doe,\cr
Some Street,\cr
Anytown}
\salutation{Dear John}
\begin{letter}
Hello.
\end{letter}
\end{document}</pre>

I did install a Gentium, but the file resolves to Gentium-R for the normal version of the font.

**Comment by alerque** [comment]
Realistically, the answer (as documented in both the readme and the manual) is that you really need the [*Gentium Plus*](https://software.sil.org/gentium/download/) font installed. SILE assumes it very early in the process of initializing the typesetter. We're kind of stuck assuming something, and that was our choice. It's the only required font. And *Gentium Regular* is not *Gentium Plus*.

Technically without it you can still typeset documents so it isn't a mandatory dependency. You can still function, but you will not be able to use the examples the way they were intended and the warning on every document you typeset about the fallback won't go away. Even if as in your document you don't output any text until after you set a new font, the typesetter still initializes before the `\font` command is run and needs to start with some kind of metrics for things like the line height and width of a space.

On a mitigation level for those that really really don't want to install the font for whatever reason you can in fact call SILE in such a way that you override the default font setting before the typesetter is initialized:

```sh
./sile -e 'SILE.settings.defaults["font.family"] = "Noto Serif"' myfile.sil
```

This will suppress the warning about not being able to find *Gentium Plus* because it looked for *Noto Serif* by default (assuming you have that font of course).

Beyond that tip, I think this comes down to a 'wontfix' scenario. The warning will go away if you install *Gentium Plus*.

@simoncozens Any input on this? I'm inclined to close in favor of the status quo, but if you feel we should rework the typesetter to delay initializing anything font related until we actually start processing text nodes or if we want to add a document level option I suppose those are options.

**Comment by ctrlcctrlv** [comment]
> there's no point keeping very old open issues if we don't plan a resolution

Not true; we may not know what to do about an issue but if it's a valid issue there's a point in keeping it. However your work today cleaning up _invalid_ old issues is appreciated!

**Comment by Omikhleia** [comment]
BTW, topic line could include "On a Mac, ..." so at glance we know it's OS-specific. (Or there could be additional labels to we know whether this is general or specific to some topic, e.g. OS issue, Font issue, &c. A standard issue template could be interesting to, so posters would be invited to at least provide some basic information in a standard readable way (SILE version, OS, etc.)

**Comment by Omikhleia** [comment]
E.g. here, perhaps the existing "builds and releases" existing label (I just noticed it) is applicable.

**Comment by alerque** [comment]
I think the original question (why the warning) was answered and we don't plan any different way of dealing with this. If there is a specific proposal for handling it differently that could be a new issue, but this one has served its purpose.
