### ISSUE TITLE
Relative indentation

### ISSUE THREAD

**Issue by ralsina** [sile-typesetter/sile#476]
First of all: I like SILE :-)

I started a rst2sile project to support generating SILE from reStructuredText.

So, I am trying to write commands to make it do what I want, and one thing reSt has is nested structure. So, I was trying to get nested indentation working. Here is my attempt:

```lua
SILE.registerCommand("relindent", function(options, content)
    local lskip = SILE.settings.get("document.lskip") or SILE.nodefactory.zeroGlue
    indent = lskip['width'] + SILE.length.parse(options["width"])
    lskip['width'] = indent
    SILE.settings.temporarily( function()
        SILE.settings.set("document.lskip", lskip)
        SILE.process(content)
    end)
end)
```
I would expect this to generate one like with a 100pt indentation and another with a 200pt indentation, but it doesn't (both lines are equally indented):

```
\begin[class=book]{document}
\script[src=packages/bullets]

\relindent[width=100pt]{1 item

2 item

\relindent[width=100pt]{2.1 item

}}
\end{document}
```

**Comment by ralsina** [comment]
Seems like I figured it out:

```lua
SILE.registerCommand("relindent", function(options, content)
    local lskip = SILE.settings.get("document.lskip") or SILE.nodefactory.newGlue('0pt')
    local indent = SILE.nodefactory.newGlue(tostring(lskip['width'] + SILE.length.parse(options["width"])))
    SILE.settings.set("document.lskip", indent)
    SILE.process(content)
end)
```

**Comment by alerque** [comment]
You might be interested in having a glance at how I've implemented [nesting lists](https://github.com/alerque/casile/blob/master/lists.lua) using an indent multiplier based on the nesting level.

**Comment by Darkyenus** [comment]
@alerque It would be great to have the list package built into the base SILE distribution. The ability to create pretty lists is currently lacking.

**Comment by alerque** [comment]
I'm re-opening this issue because, while @ralsina's solution does work, it isn't obvious and I think we should bake in a more standard way of handling this. It will be useful for more than just lists.

@Darkyenus Yes I should probably clean that up a bit and contribute it into the core. I'll need something like that anyway to typeset output from my Pandoc export.

By the way @ralsina, I'm working on a Sile writer for Pandoc that would be another (more general purpose) solution for RST→Sile.

**Comment by Omikhleia** [comment]
It's not clear what were the expectations for this issue to remain opened:
- SILE has lightweight lists since v0.13.2
- I never had any issues yet with nesting indented text (e.g. in one possible implementation of [blockquotes](https://github.com/Omikhleia/markdown.sile/blob/1dd59df0990fcb41978416e321e964ddacf1bf24/packages/markdown/commands.lua#L296) - basically the same idea as expressed above, albeit some APIs have changed since then).

Perhaps we can close that old issue, or clarify the remaining points to address?

**Comment by alerque** [comment]
Happy to re-evaluate if we missed anything, but the nested indent question was answered and we have a lists package so that seems to be the basics.
