### ISSUE TITLE
\underline underlines the indentation

### ISSUE THREAD

**Issue by pl-gauthier** [sile-typesetter/sile#489]
It seems \underline underlines the indentation if I start a new paragraph with an underlined word.

Minimal working example :
```
\begin{document}
\script[src=packages/rules]
\underline{never}
\end{document}
```

Is this the expected behavior?

**Comment by alerque** [comment]
This is expected behavior — to be expected from a bunch of typography enthusiasts that hate the concept of underlining in the first place and hence are difficult to motivate to implement such a tool thoroughly. In other words given the current implementation this is expected behavior but this should really be fixed.

**Comment by Omikhleia** [comment]
For the record, it does seem to me that PR #1334 doesn't have this issue.

**Comment by Omikhleia** [comment]
Actually the same issue as #1718
