### ISSUE TITLE
use luajit if it is present

### ISSUE THREAD

**Issue by mhosken** [sile-typesetter/sile#536]
Is there any way that sile can use luajit if it is present. sile is pretty pedestrian when run under lua but flies much like tex when run under luajit.

**Comment by alerque** [comment]
I'm not sure this is possible, executing scripts under a given interpreter is kind of up to the system. Perhaps we could setup a wrapper than checks for other interpreters and re-launches itself if possible. Also perhaps this should be a compile/install time option. We could easily have this as a compile time flag and it would get installed based on what is available on the host system.

Out of curiosity, what kind of benchmark are you getting? For example what is your compile time of the documentation PDF under vanilla `lua` vs. `luajit`?

**Comment by mhosken** [comment]
41 page font test took 18s under lua and 7s under luajit. Not as much speed up as I was expecting, but still significant when you have 20 to run.

**Comment by alerque** [comment]
A speedup of 2× runtime is nothing to turn up your nose at. I'd be all for taking any gains where we can get them. However...

Luajit appears to be only very sporadically maintained, and development is only up to par with Lua 5.1. This in itself isn't a blocker because so far we've managed to maintain compatibility with Lua 5.1 (I can't say as much for my personal project libraries, but that's my own problem). The issue I have is that the Lua 5.1 libraries on my system are nowhere near as maintained as the 5.3 ones, and as such even trying out `luajit` will require some system work. Right off the bat even though I have a `lua51-luafilesystem`  package installed both `lua5.1 $(which sile)` and `luajit $(which sile)` are unable to find the `lfs` library:

> luajit: core/sile.lua:14: module 'lfs' not found:

Were you able to run the latest HEAD version of SILE under `luajit` or just the last released version?

**Comment by mhosken** [comment]
I would try if I could get configure past not finding lua_load of all things.
