### ISSUE TITLE
Is there a way (like a package) to add en dashes, em dashes and quotation marks through ASCII characters?

### ISSUE THREAD

**Issue by hmslima** [sile-typesetter/sile#540]
I am looking for an alternative to Latex, and SILE seems to be a good candidate, but seems that in order to add en dashes, em dashes and quotation marks I have to type these characters directly in the source text, what is very laborious in my opinion.

SILE seemed to be so perfect to me. :-/

Is there any SILE package that converts --, --- and "" respectively to –, — and “”?

**Comment by alerque** [comment]
No, and this is by design. At least in the core release, SILE is designed to handle Unicode out of the box. Input is expected to be Unicode and no cutesy tricks are played mashing your content around into something other than what you input. One of the major pain points of LaTeX is that it was designed and implemented in a pre-Unicode world where ANSI was good enough for anybody. Even though there are Unicode capable LaTeX engines now, even they are so layered with patches and kludges to make it all work that introducing people to writing in TeX is daunting at best and completely untenable at worse.

You are of course free to do whatever you want. An input filter that substitutes these strings would be a trivial matter of a couple lines of Lua and you could use it as your own package. Curly quotes are a little more complicated as they require context to correctly guess, but it's still workable.

On the other hand I would suggest an alternate approach: fix your input. If entering en- and em- dashes is laborious, fix that. On my computers it's not. The solutions for this vary between platforms, but on Linux this is as easy as tapping the <kbd>Compose</kbd> key and then typing two regular dashes for an en-dash or three for a em-dash. The beauty of this is that it works anywhere in any program, it's part of the input method.

Other platforms have (or can be fixed to have) similar techniques that makes entry quite easy.

Alternatively you can post-process your input. This is something I sometimes do for smart quotes. My source documents are often Markdown and converted to SILE for typesetting. As part of that process I run a couple search and replaces to cleanup any quotes that have been left "computer style" (straight). Typing those is easy too, but the one extra press it takes me is sometimes overlooked in the writing and editing stages.

**Comment by hmslima** [comment]
Well, I solved the problem by installing the addons [unicode](https://github.com/chrisbra/unicode.vim) and [UniCycle](https://github.com/vim-scripts/UniCycle) into Vim. UniCycle is the best because it converts the characters during the very typing moment, I use unicode.vim for other symbols.

_My problem now is to install SILE in my system._ :-/

.

**But I wanna make some comments:**

.

> No, and this is by design. At least in the core release, SILE is designed to handle Unicode out of the box.

And that is great! Especially for me that sometimes work with very different writing systems.

> Even though there are Unicode capable LaTeX engines now, even they are so layered with patches and kludges to make it all work that introducing people to writing in TeX is daunting at best and completely untenable at worse.

Yes, surely the installation of Latex here took more than 2GB of my hard drive (due the configuration I had to do here, 2GB is a lot of space. It's a long story and it doesn't matter here...)

> The solutions for this vary between platforms, but on Linux this is as easy as tapping the `Compose` key and then typing two regular dashes for an en-dash or three for a em-dash

The problem is that my ABNT2 keyboard doesn't have this key. But seems that I can create a compose key by configuring my keyboard, I'll search about this later.

**Comment by hmslima** [comment]
Thank you for your advice, @leorosa

**Comment by Omikhleia** [comment]
Answered and closed?

**Comment by alerque** [comment]
Yup, I don't think there is anything to do here.

Just a note of my "solutions" for this is doing most content authoring in Markdown, and using Pandoc to convert it to SILE. This allows the smart-typography extensions to catch and fix things like quote directions, en/em dashes entered as `--`/`---`, and more.

**Comment by ctrlcctrlv** [comment]
There's also [SILE TeXmode](https://github.com/ctrlcctrlv/sile-texmode) for the adventurously stupid. I'm still stupid but less adventurous so I no longer use it, but someone else may want to.
