### ISSUE TITLE
Enforce good commit messages

### ISSUE THREAD

**Issue by simoncozens** [sile-typesetter/sile#549]
Working on a 0.9.5 release changelog and it's horrible because I am undisciplined.

I would like a git commit hook which checks the commit messages is formatted as `[area] ...` where area is taken from a given list of areas.

**Comment by alerque** [comment]
You're telling me! If it's hard for you to figure out what you mean reading your own commit messages, imagine the rest of us out here.

I don't think a commit hook is the right solution, because there are times when hacking on stuff and you just want to cobble together a commit as a rollback point in case something goes sideways while hacking. The issue here is that such development sessions should get cleaned up using rebase before they are pushed to any permanent branch. Some needlessly incremental commits can be combined (debounced in hardware lingo), others just reworded to properly describe what they do. Requiring proper commit messages should happen before  anything hits master or devel branches, but I wouldn't want my local machines slowing up the hacking process before the churn dies down.

Maybe just a reminder message in the commit hook, and an actual requirement on master/devel merges.

**Comment by alerque** [comment]
Also just a reminder, besides the full commit change log the [closed issues in a milestone](https://github.com/simoncozens/sile/milestone/4?closed=1) should be a pretty good summary of what goes into a release — especially if feature branches are used and put through the PR workflow even for  little things we hack on independent of any listed issues. Besides having benefits for testing like CI checks, the merge workflow also groups commits by topic and the commit graph shape starts telling more of a story.

**Comment by rjmunro** [comment]
I would start by blocking commits to master and making all commits go though a branch and a PR. That way other people can review them, and the detail of the PR. You can list all the merges into master with `git log --first-parent` - this will correspond to all the pull requests, which should be a better summary of the changes since the last release.

**Comment by simoncozens** [comment]
We did that. What I'm looking to do is ensure that commits are categorised by bug fix, new feature, code cleanup, etc.

**Comment by alerque** [comment]
I'm not sure how much sense it really makes to have subject line tags for `[bugfix]`, `[feature]`, etc. In my experience following the Linux kernel's (and Progit's) guidelines on always starting commit messages with imperative present tense verbs pretty much solves that while still leaving some room for things that don't neatly fit into one box or the other.

> Describe your changes in imperative mood, e.g. "make xyzzy do frotz" instead of "[This patch] makes xyzzy do frotz" or "[I] changed xyzzy to do frotz", as if you are giving orders to the codebase to change its behavior.

Noting which areas of the code are effected makes a lot more sense to me because it cuts down on the verbosity of the messages _and_ makes it easier to skip over things that aren't what you're looking for. To this end we would really want a canonical list of areas. In the past few weeks we've used some ad-hoc ones but they aren't really very normalized yet.

* build
* docs
* input
* package
* cli
* shaper
* typesetter
* backend
* ???

**Comment by rjmunro** [comment]
@alerque You can do `git commit -n` to skip the commit hook for quick temporary hacks.

**Comment by simoncozens** [comment]
When we're writing the release notes, the most important thing is not so much the area of operation but whether a change is user-facing or just internal reorganisation. A lot of our development (unfortunately) is things like adding debugging information, tidying up code, improving error messages and so on; stuff which isn't very exciting for a user.

Within the user-facing changes, the most important things to know about are:

* Does this let me do something I couldn't do before? (e.g. `[feature]`, `[package]`)
* Does this improve/add support for particular a `[language]`?
* Is this a general `[improvement]` that I might notice? (e.g. better hyphenation, float handling, etc.)
* Does this `[fix]` something that was broken before?
* Does this introduce a`[backward-compatibility]` issue?
* ...

**Comment by alerque** [comment]
For further reading: https://medium.com/jobtome-engineering/how-to-generate-changelog-using-conventional-commits-10be40f5826c

**Comment by alerque** [comment]
I'm not actually a huge fan of any of the normalized systems I've seen so far, but I am a huge fan of having a normal and sticking to it — and even if we don't like every detail having an outside spec that we follow will make it a lot easier to conform _and_ means we can use other people's tooling.

To that end so far I see:

* [Conventional Commits](https://www.conventionalcommits.org), [commitlint](https://github.com/conventional-changelog/commitlint) and [commitlint-bot](https://github.com/z0al/commitlint-bot)
* [git journal](https://github.com/saschagrunert/git-journal)
* [git good commit](https://github.com/tommarshall/git-good-commit)
* [turbo git](https://github.com/labs-js/turbo-git)
* [fit commit](https://github.com/m1foley/fit-commit)
* [gommit](https://github.com/antham/gommit)
* [Automatic Github Changelog Generator](https://www.bram.us/2019/04/12/automatic-github-changelog-generator/)

Of those the first one seems to have the most momentum behind it. Should we head that way?

Also check out [Gitlab's CHANGELOG system](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/development/changelog.md) for some heavyweight action!

**Comment by simoncozens** [comment]
I like the commitlint idea a lot, and agree with the idea of reusing other people’s tooling. Let’s set that up, with the bot. And autogenerating the changelog would be fine if supplemented with manual curation.

**Comment by alerque** [comment]
Re-opening because even with the configuration in the master branch now the commitlint bot is _not_ doing it's job. It's approving messages that should be rejected by the filter.

Locally it works fine. For example if I run `commitlint --from upstream/master --to HEAD` on my PR's I get a detailed breakdown of what commits meet approval and which don't, but the same results are not being offered as feedback on PRs.

**Comment by alerque** [comment]
So ... the commitlint-bot is actually working, but it [does not yet support custom configuration](https://github.com/z0al/commitlint-bot/issues/1) so it is only using it's default rule set, not the one I configured for this repository. I'm looking into having Travis handle this instead.

**Comment by alerque** [comment]
Per this comment: https://github.com/z0al/commitlint-bot/issues/1#issuecomment-539507835 ...

It looks like the way to do this is using GH Actions and a separate workflow for commitlinting from the rest of our CI jobs.

**Comment by alerque** [comment]
Fixed by #752.
