### ISSUE TITLE
Discressionaries in \href aren't counted towards width

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#583]
Our temporary hack for #355 has surfaced another bad side effect. Having such a discretionary character inside a `\pdf:link{}` causes SILE to miscalculate the width of the hbox and the layout of the rest of the line is off by the width of the apostrophe that was included (but not calculated in the width).

```TeX
\begin[papersize=a6]{document}
\script[src=packages/url]
\begin{script}
SILE.registerCommand("ah", function ()
  SILE.call("discretionary", { prebreak = "-", replacement = "’" })
end)
\end{script}
\language[main=tr]
\font[language=tr]
(\href[src=""]{Yasa\ah{}nın Tekrarı 19:21})
\end{document}
```

![image](https://user-images.githubusercontent.com/173595/56499512-62528200-650f-11e9-83ed-3d626f44eb19.png)

Oddly enough, another different breakage occurs in the event of an `\href` without the `src` attribute:

```TeX
(\href[]{Yasa\ah{}nın Tekrarı 19:21})
```

![image](https://user-images.githubusercontent.com/173595/56499614-c5441900-650f-11e9-9b5d-9a171af71370.png)

Either way the  width is miscalculated, but in one iteration the discretionary doesn't even get drawn until after the link!

Note the MWE is in Turkish because that's what I paired it down from and where it finds a real-world manifestation, but it's not actually specific to the language.

**Comment by alerque** [comment]
c.f. #1362

It isn't just inside hrefs that is a problem, discretionaries aren't being added up right across a whole line.

**Comment by Omikhleia** [comment]
First, assuming the `hbox` logic (currently used in `\href` via `pdf:link`) might be the culprit, I simplified the MWE as follows:

```
\begin[papersize=a6]{document}
\neverindent
\define[command=ah]{\discretionary[prebreak=-, replacement=’]}
\language[main=tr]

(\hbox{Yasa\ah{}nın Tekrarı 19:21}) with hbox

(Yasa\ah{}nın Tekrarı 19:21) without hbox

\end{document}
```

The issue is indeed observed:

![image](https://user-images.githubusercontent.com/18075640/227813014-a946fafe-8737-4678-8edd-228426b0b3c2.png)

Then, trying this fix (on the hbox building logic, from the revised implementation in #1702)

```
diff --git a/typesetters/base.lua b/typesetters/base.lua
index 22651ad0..07004095 100644
--- a/typesetters/base.lua
+++ b/typesetters/base.lua
@@ -817,6 +817,9 @@ function typesetter:makeHbox (content)
         d = attr.depth > d and attr.depth or d
         l = l + attr:lineContribution():absolute()
       end
+    elseif node.is_discretionary then
+      recentContribution[#recentContribution+1] = node
+      l = l + node:replacementWidth()
     else
       recentContribution[#recentContribution+1] = node
       l = l + node:lineContribution():absolute()
```

Yay! It seems to do the trick...

![image](https://user-images.githubusercontent.com/18075640/227813408-27e04962-5687-48d7-9470-4b96c251f252.png)

**Analysis**

In the default case, we use `node:lineContribution()`, which evaluates to the node width in horizontal writing direction (and to the height in vertical direction). This happens to be 0 in that case... Since the hbox will not be line-broken, the "replacement" content should apply here, if I understand that part correctly. 

Things I don't fully get however:
- I can't fully make sense of what `typesetter.computeLineRatio` does with discretionary nodes (which I checked out of curiosity, since it ought to do something similar for line width and ratio computation, but most of it still eludes me)...
- I've no idea why these things have a height but no depth, and if we should do something with `node:replacementHeight()`...
- I have no idea how TTB/BTT is supposed to consider them...
- I wasn't able to observe the other "different breakage" in the event of an `\href` without the `src` attribute.

Still, it seems this could be an acceptable fix (perhaps with an extra comment referring to this issue). @alerque What do you think? You might have a better understanding of these "discretionaries" with special replacements (the "regular" ones don't have a replacement, apparently).

**Comment by Omikhleia** [comment]
> I can't fully make sense of what `typesetter.computeLineRatio` does with discretionary nodes 

Erm... It's **entirely** wrong when there are discretionary replacements, no?

MWE:

```
\begin[papersize=a6]{document}
\neverindent
\define[command=ah]{\discretionary[prebreak=-, replacement=¤]}

loremipsumdo\ah{}lor
lor\ah{}emip\ah{}sumdo\ah{}lor
lor\ah{}emip\ah{}sumdo\ah{}lor
lor\ah{}emip\ah{}sumdo\ah{}lor
lor\ah{}emip\ah{}sumdo\ah{}lor
lor\ah{}emip\ah{}sumdo\ah{}lor
lor\ah{}emip\ah{}sumdo\ah{}lor

\end{document}
```

Observed:

![image](https://user-images.githubusercontent.com/18075640/227820488-38ae43e6-1e85-4215-9203-b80311cd8d45.png)

An attempt....

```
@@ -715,7 +715,7 @@ function typesetter.computeLineRatio (_, breakwidth, slice)
       if slice[n].parent then
         slice[n].parent.hyphenated = true
       end
-      naturalTotals:___sub(slice[n]:replacementWidth())
+      -- naturalTotals:___sub(slice[n]:replacementWidth())
       naturalTotals:___add(slice[n]:prebreakWidth())
       slice[n].height = slice[n]:prebreakHeight()
       break
@@ -742,7 +742,7 @@ function typesetter.computeLineRatio (_, breakwidth, slice)
       skipping = false
     elseif node.is_discretionary then
       skipping = false
-      if node.used then
+      if not node.used then
         naturalTotals:___add(node:replacementWidth())
         slice[i].height = slice[i]:replacementHeight():absolute()
       end
@@ -752,7 +752,7 @@ function typesetter.computeLineRatio (_, breakwidth, slice)
   end
 
   if slice[1].is_discretionary then
-    naturalTotals:___sub(slice[1]:replacementWidth())
+    -- naturalTotals:___sub(slice[1]:replacementWidth())
     naturalTotals:___add(slice[1]:postbreakWidth())
     slice[1].height = slice[1]:postbreakHeight()
   end
```

![image](https://user-images.githubusercontent.com/18075640/227820909-e4ecd745-2f67-4ce3-a775-071f0b2381f7.png)

**Comment by Omikhleia** [comment]
... And the latter things above point to #1528
