### ISSUE TITLE
Discussion: Providing compatibility of TeX documents?

### ISSUE THREAD

**Issue by elliott-wen** [sile-typesetter/sile#664]
Hi, there. I am a developer of SwiftLaTeX.

I think SILE is really an amazing and future-proof engine. 

Currently, I am thinking incorporating the PdfTeX engine with SILE to provide backward compatibility of TeX documents.  The basic idea would be use PdfTeX to parse TeX documents and generate box lists, which will then fed into SILE. 

Not sure that's a good idea. If yes, I may start implementing and send some pull requests.

Any suggestion?

**Comment by alerque** [comment]
I'm really not sure what you are suggesting here. Do you want to embed SILE in PdfTeX? Or the other way around? What advantage do you hope to gain? What is the scenario or use case where this would be useful?

**Comment by elliott-wen** [comment]
I meant integrating PdfTex to SILE such that users can benefit from the
ecosystem of TeX community?

Cheers

**Comment by alerque** [comment]
Personally (and as a long time and still LaTeX user) my gut level feeling is that dragging the TeX ecosystem baggage into SILE would be a step backwards for everybody. It's already so similar in some ways it's hard to break old TeX habits, but radically different enough that one ~~can't~~ shouldn't just start tying to replicate the functionality of TeX packages because the processing paradigm is fundamentally different and each thing needs to be re-imagined rather than just rehashed.

That being said I'd be interested in seeing a mockup of what you envision would happen. There's obviously nothing to stop you from implementing whatever you want (might I suggest if you want to play around with something that LuaLaTeX would be a better fit for a cross-breed than PdfTeX?) but for the purposes of discussion just a mockup of what a document might look like, what a command might be, and what the output would look like would suffice. I suspect looking at such a mockup it will be easier to either see why it would be a good idea or point out why it wouldn't be worth while.

**Comment by alerque** [comment]
See also discussion in relation to TeX compatibility in #947. I still don't have any clear idea of what you had in mind here, but...

* If it involves extending SILE to support content programmed for TeX using TeX ecosystem packages, then I don't think we plan on building that into SILE. You're still quite welcome to fork if you want to make it happen and prove us wrong. A tech demonstration and use case would put this in a different light.

* If it involves extending some legacy tool to call out to SILE to get work done, sure you're welcome to try, but I don't see what you need from this end.

Since we don't really envision SILE re-implementing TeX or being backwards compatible with it, I think I'm going to close this issue for now. If I'm miss-understanding what you had in mind feel free to come pack with a description of the parts and what would be changing to support what. We're happy to consider any way SILE can be useful, but at the current time don't see taking either the roads LuaLaTeX or LaTeX3 are walking.
