### ISSUE TITLE
Build Problems On Fedora 30 (x86_64)

### ISSUE THREAD

**Issue by nobozo** [sile-typesetter/sile#671]
1) Running bootstrap.sh results in
"autoreconf: 'configure.ac' or 'configure.in' is required"

This is in spite of configure.ac existing in the current directory.

2) Running ./configure results in
"configure: error: cannot find Lua library zlib - install from luarocks package lua-zlib"

This is in spite of the fact that I installed all the listed lua libraries. (The others, e.g. lpeg, lxp are found).

Rerunning luarocks install lua-zlib says
"lua-zlib 1.2-0 is now installed in /usr (license: MIT)"

and then running ldconfig doesn't change anything. If I run updatedb, and the locate lua_zlib
I only see

/usr/local/src/sile-0.9.5.1/vendor/lua-zlib/lua_zlib.c

What am I doing wrong?

**Comment by alerque** [comment]
One thing you didn't say is what version you are trying to setup. Are you using a source tarball of the last tag or master or git or what? That will make a big difference to answering this.

The build an install procedure is kind of in transition in `master` right now. That being said it should still work. The one major difference is that you have a choice of using system Lua libraries or downloading and using project-local copies of them as part of the build (`./configure --with-system-luarocks` or `./configure --without-system-luarocks` + `make installrocks`)

Please let us know which version you're trying to compile.

P.S. We're pretty close to another release, making sure it installs well on a variety of systems is the main thing left I'm working on before making it, so how this works out of Fedora is kind of important. I'll try to get you through this, but I'm also taking notes on anything that needs fixing.

**Comment by nobozo** [comment]
On 10/4/2019 1:01 PM, Caleb Maclennan wrote:
> One thing you didn't say is what version you are trying to setup. Are 
> you using a source tarball of the last tag or master or git or what? 
> That will make a big difference to answering this.

I downloaded

https://github.com/sile-typesetter/sile/archive/v0.9.5.1.tar.gz

from the GitHub releases page.

(One minor nit, but since you're trying to improve the
install process - the bz2 ball is called sile-0.9.5.1.tar.bz2
but the tar ball is called v0.9.5.1.tar.gz. Wouldn't it make
more sense if were called sile-0.9.5.1.tar.gz? Same for the zip ball.)

> The build an install procedure is kind of in transition in |master| 
> right now. That being said it should still work. The one major 
> difference is that you have a choice of using system Lua libraries or 
> downloading and using project-local copies of them as part of the build 
> (|./configure --with-system-luarocks| or |./configure 
> --without-system-luarocks| + |make installrocks|)
> 
> Please let us know which version you're trying to compile.

I was following the instructions in section 2.2.2 in the
sile-0.9.5.pdf manual. This doesn't mention options to configure.

> P.S. We're pretty close to another release, making sure it installs well 
> on a variety of systems is the main thing left I'm working on before 
> making it, so how this works out of Fedora is kind of important. I'll 
> try to get you through this, but I'm also taking notes on anything that 
> needs fixing.

I'd be happy to help in any way I can.

Cordially,
Jon Forrest

**Comment by alerque** [comment]
Hey Jon,

At this point as we are close to another release with major changes to the build system since the last one it would be more useful to us if you used a more recent release than the tagged version. I suspect it will actually make things easier for you too, the last release had some issues getting along with some host systems (hence the overhaul in the first place!).

From the main repository page on Github there is a "Clone or Download" button that will let you checkout the repository using `git` <strike>or download a ZIP of the current state. I would start there.</strike> ... I just realized the ZIP won't work for you without system dependencies worked out first. Right now without a source build (also in the works) checking out the git repo is the only way to get it.

How about I build you a source tarball...

**Comment by alerque** [comment]
Please have a go with this source build: [sile-v0.9.5.1-320-g18a3b2c0.zip](https://github.com/sile-typesetter/sile/files/3710737/sile-v0.9.5.1-320-g18a3b2c0.zip)

Presuming you have `lua`, `harfbuzz`, and `icu` installed on your system already, you should be able to:

1. Extract this to a new folder
2. Run `./configure` to update the configuration based on your system. Note that the configure status file included in this zip is already setup with `--without-system-luarocks` and `--without-system-libtexpdf` and those respective collections of assets are bundled in the zip alongside SILE's source. You shouldn't need to specify those options again, just run configure so that it finds the paths to things on your system such as the Lua interpreter, etc.
3. Run `make`

That should get you a working build that you can run from that folder with `./sile`. If that works you should also be able to do a `sudo make install` to set it up on your system.

Please let me know how this goes. I'll be making any necessary adjustments on this end so this routine works. There shouldn't be any other hoops to jump through.

**Comment by nobozo** [comment]
On 10/9/2019 11:22 PM, Caleb Maclennan wrote:
> Please have a go with this source build: sile-v0.9.5.1-320-g18a3b2c0.zip 
> <https://github.com/sile-typesetter/sile/files/3710737/sile-v0.9.5.1-320-g18a3b2c0.zip>

Better. I extracted the zip file into a new directory, and did what you
said. But the make failed with the following message:

cp .libs/justenoughharfbuzz.so .libs/justenoughfontconfig.so 
.libs/justenoughlibtexpdf.so .libs/fontmetrics.so .libs/svg.so 
.libs/justenoughicu.so ../core
make[1]: Leaving directory '/usr/local/src/sile-v0.9.5.1-320-g18a3b2c0/src'
make[1]: Entering directory '/usr/local/src/sile-v0.9.5.1-320-g18a3b2c0'
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
make[1]: *** No rule to make target 'sile-dev-1.rockspec', needed by 
'lua_modules'.  Stop.
make[1]: Leaving directory '/usr/local/src/sile-v0.9.5.1-320-g18a3b2c0'

I hope this helps.

My power is back on again so I should be able to respond more quickly
than last time.

Jon

**Comment by alerque** [comment]
Try this build: [sile-v0.9.5.1-321-gcc6fb851.zip](https://github.com/sile-typesetter/sile/files/3718378/sile-v0.9.5.1-321-gcc6fb851.zip)

**Comment by nobozo** [comment]
On 10/11/2019 8:38 AM, Caleb Maclennan wrote:
> Try this build: sile-v0.9.5.1-321-gcc6fb851.zip 

Better again. Now I got

Installing https://luarocks.org/luasec-0.8.1-1.src.rock

Error: Failed installing dependency: 
https://luarocks.org/luasec-0.8.1-1.src.rock - Could not find header 
file for OPENSSL
   No file openssl/ssl.h in /usr/local/include
   No file openssl/ssl.h in /usr/include
   No file openssl/ssl.h in /include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR 
or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luasec OPENSSL_DIR=/usr/local
make[1]: *** [Makefile:1012: lua_modules] Error 1
make[1]: Leaving directory '/usr/local/src/sile-v0.9.5.1-321-gcc6fb851'
make: *** [Makefile:548: all-recursive] Error 1

I fixed this by running

dnf install openssl-devel

I then ran ./sile on the test.sil document from the website
and it worked. I checked the generated pdf, which looks fine.

Thanks for your help!
Jon

**Comment by alerque** [comment]
Thanks for the patience through the process @nobozo. I'm glad you got it working in the end ... and also glad to know our process is _close_ to being right for the next release cycle. I've fixed the missing file issue and made a note to document the *openssl* dependency (that has bitten us before, it's kind of a bugger because each platform handles it differently). Hopefully with the source build cooperating with just the usual `./configure && make`, setting up honest-to-goodness Fedora packages will be possible for future releases.

**Comment by alerque** [comment]
Just a comment on your nit about version numbering @nobozo. I hear you! We're actually standardizing on this in the other direction (always including the `v` as part of the version string) for now. I don't particularly like it but it is kind of what the GNU Autoconf tools push us towards and quite a standard practice. The version will be composed of 3 semantic numbers, but the version **string** will include 'v' as well as any other information about the release. For non-tagged builds this may include a counter since the last tag and the git commit short hash. This could also include pre-release info like `-rcN`, although to date we haven't used that.

The string in future releases should be consistent in the git tag, the zip / tarball filenames, SILE's internal version string, etc.
