### ISSUE TITLE
Handle guillemots properly in French

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#704]
As turned up in #702 (and should have turned up in #621 but didn't) we're still not handling guillemots correctly in French texts.

* [ ] Characters `«`, `‹`, `›`, and `»` should all get thin non-breaking spaces before and after them respectively. Adding the latter two to the `fr.highpuctuation` setting would work for the trailing ones but the whole system needs to be adapted for the leading ones.
* [x] Figure out what to do with non-Unicode variants in input, `<<`, `<`, `>`, and `>>`. My thought is to ignore them, but I don't type French either so I don't know how practical that is.
* [ ] Add or adapt a test to show input with and without manual spaces (similar to 621) but that also catches the marks at a line break so we can prove the breaks aren't happening at the wrong place.

**Comment by alerque** [comment]
Also look into other languages with nearly identical issues to see if the fix(es) apply:

From [Wikipedia](https://en.wikipedia.org/wiki/Non-breaking_space#Width_variation):

> U+202F   NARROW NO-BREAK SPACE (HTML &#8239; · NNBSP). It was introduced in Unicode 3.0 for Mongolian, to separate a suffix from the word stem without indicating a word boundary. It is also required for big punctuation in French, sometimes inaccurately referred to as "double punctuation" (before ;, ?, !, », › and after «, ‹; today often also before :), in Russian (before em dash [—]), and in German between multi-part abbreviations (e.g. "z. B.", "d. h.", "v. l. n. r."). When used with Mongolian, its width is usually one third of the normal space; in other contexts, its width is about 70% of the normal space but may resemble that of the thin space (U+2009), at least with some fonts. Also starting from release 34 of Unicode Common Locale Data Repository (CLDR) the NNBSP is used in numbers as thousands group separator for French locale.

**Comment by OlivierNicole** [comment]
> Characters «, ‹, ›, and » should all get thin non-breaking spaces before and after them respectively.

To the best of my knowledge, hardly anyone uses `‹`, `›`. Only the *Guide du typographe romand* (Switzerland) advocates for their use. There doesn't seem to be much cost in supporting them, however.

> Figure out what to do with non-Unicode variants in input, `<<`, `<`, `>`, and `>>`. My thought is to ignore them, but I don't type French either so I don't know how practical that is.

Given their infrequency of use, I don't think it's worth substituting `<`, `>`. Regarding regular guillemets, I guess it depends on what is SILE's policy regarding such character substitutions. I recall reading in the manual that there is no plan of supporting them.

**Comment by OlivierNicole** [comment]
> I recall reading in the manual that there is no plan of supporting them.

P.S. reference https://github.com/sile-typesetter/sile/blob/master/documentation/sile.sil#L438

**Comment by simoncozens** [comment]
I am also inclined not to change the spacing of <> - it's attaching semantic significance to something that we've already said we're not going to muck around with. I think `highpunctuation` is the wrong place for guillemots, because... well, they're not high punctuation. :-) We have to deal with them separately.

**Comment by OlivierNicole** [comment]
Since `‹ ›` are not used for anything else in French, it probably won't mess anything up to adjust spacing around them.

I don't know anyone who uses ASCII glyphs `<< >>` in their texts. When we are stuck with ASCII or do not have a proper keyboard layout, we prefer to use the ASCII quotation mark `"`.

**Comment by alerque** [comment]
@simoncozens I already tried implementing them as high-punctuation and that didn't go well. Clearly they are not the same as high-punctuation and need to be handled as something else and probably some*where* else too. See #705 and feel free to hack on that branch if you do see how you think it should be done, I am back to messing with other stuff.

**Comment by simoncozens** [comment]
Will try to take a look

**Comment by Omikhleia** [comment]
I had a look at the pull request mentioned above, but it doesn't do the job properly (yet) if we want good French typography.

Let's go back a the proper rule definitions...

Sources:
- Lacroux, _Orthotypographie_, entry "Espace"
- LaTeX babel-french package (as it got inputs from Thierry Bouche, also a good typographer)

Punctuations
- So-called high punctuations are `!`, `?`, `;` and `:`
- Between a letter (or digit) and these high punctuation marks
  - For `!`, `?` and `;` a thin non-breakable space should be inserted
  - For `:` there are two schools, either a regular non-breakable space or (sometimes considered better, but I would say much rarer) a non-breakable space smaller than the justification space but greater than a thin space.
- Note the "between a letter or digit and these high punctuation"! It is not a very general description of the exceptions, but :
  - One shall have no space inside `(?)`, `?!`, `[!]`, etc.
  - Normally, as per the rules, also no space after the dots, e.g. in `…?` etc. (I mention this one explicitly for it is more debatable maybe)
  - But Lacroux doesn't mention all exceptions explicitly, and it seems to me that a space should be inserted after `)` and closing ddduillemots (of all types, so `»`, `›` and also `”`) - e.g. after quotations or parenthesized words. Likewise after `]` since bracketed words may represent an omission, etc. So basically, as a rule of thumb, any closing punctuation.
  
Guillemots
- In French from France or Canada, these are `«` and `»` (the so-called double or typographical guillemots)
- In French from Swiss, in addition, `‹` and `›` (the so-called chevrons or simple guillemots), I don't see any reason not to support them.
- They do not belong to the "high punctuations" (strictly speaking)
  - (France, Canada) They should always use regular non-breakable space or (considered better) a non-breakable space smaller than the justification space but greater than a thin space (= same type of special space as for the colon above)
  - (Swiss) Well the Swiss prefer a thin unbreakable space... so it should be configurable at least.

To summarize my understanding:
- A single setting `languages.fr.punctuationspace` is not sufficient, we need three settings (as does the babel-french package for LaTeX, actually) such as:
  - `languages.fr.colonspace`= a non-breakable inter-word space or (better) slightly smaller. Theoretically, it should be stretchable and shrinkable.
  - `languages.fr.guillspace = a non-breakable space, for which Thierry Bouche suggested 80% if an inter-word space with reduced stretchability, and babel-french implements it as "(0.8 x inter-word space) plus (0.3 x inter-word stretch) minus (0.8 x inter-word shrink)
  - `languages.fr.thinspace = a non-breakable fixed thin space, babel-french implements it as 0.5 x inter-word space (without stretch or shrink).
- The logic should differ:
  - Before `;`, `!` and `!`
    - Ignore any white space the user might have typed
    - If previous non-white character is a letter or digit or a closing punctuation, insert `languages.fr.thinspace`
  - Before `:`
    - Ignore any white space the user might have typed
    - If previous non-white character is a letter or digit or a closing punctuation, insert `languages.fr.colonspace`
  - Before `»` and `›` 
    - Ignore any white space the user might have typed
    - Always insert `languages.fr.guillspace`
   - After `«` and `‹`
      - Ignore any white space the user might have typed
     - Always insert `languages.fr.guillspace`
   - In the above, if doable, "any white space" is the standard space, but also any Unicode space the user might have been tempted to use explicitly (e.g. U+202F, U+2009, etc.)
   - I don't know when the processing occurs, but I am concerned how it will behave if there's a command call before a punctuation or quote, e.g. `It would be \em{something} !` - There would always be edge cases, I guess, so maybe one needs commands to explicitly add the correct glue (if missing) or for it to be removed (if wrongly inserted) ?
  
Some test case
```
Un ! Deux ? Trois !? Quatre !!!
Cinq : « Six ‹ Sept ›`Huit » !
[Neuf] : (Dix) ! \em{Onze} ! \em{« Douze »} !
Treize ; Quatorze … !
```

**Comment by Omikhleia** [comment]
For the record, I am taking up on this one
