### ISSUE TITLE
Multiple fonts with font:add-fallback causes verbose warnings

### ISSUE THREAD

**Issue by hajimehoshi** [sile-typesetter/sile#706]
Hi, I tried SILE with Japanese texts.

When I want to use different fonts for different language, `packages/font-fallback` sounds the way to go, but this causes verbose warnings:

```hello.sil
\begin[class=book,papersize=182mm x 257mm]{document}

\script[src=packages/font-fallback]

\font[family=Roboto,size=3.2mm]
\font:add-fallback[family=Noto Serif CJK JP]

こんにちは! Hello!

\end{document}
```

```
$ sile hello.sil
This is SILE 0.9.5.1
<hello.sil>

! Glyph こ not found in Roboto

! Glyph ん not found in Roboto

! Glyph に not found in Roboto

! Glyph ち not found in Roboto

! Glyph は not found in Roboto
[1] [2] 
```

This warning is annoying. Is there a way to suppress this, or is there a better way to mix multiple fonts?

Thanks,

**Comment by alerque** [comment]
I agree this is too verbose, and I couldn't find a way to make it quieter, so I made one. The use of warning messages was too aggressive because this is _expected_ behavior when using font fallbacks. I changed that message to be behind a `-d font-fallback` debug flag so you can still see it if you want, and instead changed what was previously a debug message into a warning for the case when no fallback was found for a glyph. If the fallbacks fail entirely to come up with a glyph, now you get a full warning.

I hope that suites your usage better. I know it will be nicer for my usage, but if the message are confusing or you can think of further improvements please feel free to speak up.

**Comment by hajimehoshi** [comment]
Thank you for the quick fix! I now installed SILE via brew, but I'll try to use the latest one later.

**Comment by alerque** [comment]
@hajomehoshi If the Homebrew recipe is still setup properly (I'm not sure it is) you should be able to update to the latest git version by using the `--HEAD` flag. On the other hand if that does not work please open an issue about it specifically because there are a number of changes to the way the build and dependencies work since the last release. We're pretty close to a new release mostly for the purpose of ironing out the build and install process and we'll definitely try to get the Homebrew experience smoothed out along the way.

**Comment by hajimehoshi** [comment]
Thanks. I know `--HEAD` flag is useful but I want to try to build it myself so that I might be able to analyze SILE and perhaps contribute to it :)
