### ISSUE TITLE
Lua check errors on GitHub actions

### ISSUE THREAD

**Issue by hajimehoshi** [sile-typesetter/sile#719]
```
Checking .busted                                  OK
Checking .luacheckrc                              OK
Checking classes/bible.lua                        OK
Checking classes/book.lua                         OK
Checking classes/diglot.lua                       OK
Checking classes/docbook.lua                      OK
Checking classes/jbook.lua                        1 warning

    classes/jbook.lua:32:15: unused argument self

Checking classes/jplain.lua                       OK
Checking classes/letter.lua                       OK
Checking classes/markdown.lua                     OK
Checking classes/pecha.lua                        OK
Checking classes/plain.lua                        OK
Checking classes/triglot.lua                      OK
Checking core/base-shaper.lua                     1 warning

    core/base-shaper.lua:15:1: setting non-standard global variable makenodes

Checking core/baseclass.lua                       OK
Checking core/break.lua                           OK
Checking core/cairo-output.lua                    OK
Checking core/colorparser.lua                     OK
Checking core/debug-output.lua                    OK
Checking core/dummy-output.lua                    OK
Checking core/font.lua                            OK
```

I think the tests should keep green. I was wondering if it would be feasible to suppress these errors.

**Comment by alerque** [comment]
The luacheck test was just recently introduced (see #681). I am in the process of working through the code based dealing with the things it brings up. Many of them are just lint warnings that could be suppressed, but I've found fixing them instead of suppressing them has actually revealed a lot of very real problems in the code. I have fixed hundreds and hundreds of them and in the process found a couple dozen things that were actually lurking bugs that hadn't manifest yet.

I'm going to keep working through these to get the check green, but as you can see from #682 this is not an easy chore. In the mean time I don't think artificially setting the test to green when it actually isn't is a good idea. It's marked as a non-required test until we can reasonably expect PRs to pass.

**Comment by alerque** [comment]
I guess what I'm saying is that if you just suppress the warnings and show me a green check mark I'll lose motivation to actually fix the problem. It's already a royal pain in the behind, but at least I've been working on it every day and making progress. As long as the motivation is working...

**Comment by hajimehoshi** [comment]
OK I agree just suppressing is not good in the long run. Then I was wondering if it'd be possible to fix jbook.lua and base-shaper.lua's issues, but #682 is the work to do this. Is my understanding correct?

I love SILE since this is an 'understandable' TeX and seems promising to me. I'd like to contribute this when I have bandwidth.

**Comment by alerque** [comment]
This has been fixed for a while. Luacheck linting is 100% green with only minimal exceptions for some things we do on purpose knowing the consequences. It's also a required tests for merging PRs.
