### ISSUE TITLE
Figure out how to store & update documentation translations

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#737]
Because it's [already too late](https://github.com/shirat74/SILE-doc_ja) to get started.

See also #665 and friends for potentially localizing the UI, error messages, etc.

**Comment by Omikhleia** [comment]
Regarding the Japanese translation...

The last translation in [this repository](https://github.com/shirat74/SILE-doc_ja) was the 0.9.2 SILE manual from Dec. **2015**.
There was no update, and no answer either after a [query made in **2019**](https://github.com/shirat74/SILE-doc_ja/issues/1). Eight years have passed, so, without any sign of activity.

Regarding translations in other languages - There are none known. We are four years after this issue was opened... Besides, SILE's manual still evolves a lot, so it's quite impractical to consider at this point.

I'm therefore closing/rejecting this issue (inactive, unaddressed, beyond the scope and ability of the dev team).
Feel free to re-open or address in a new issue, if things move on in one way or another.
