### ISSUE TITLE
Instructions don't mention need for libssl-dev

### ISSUE THREAD

**Issue by RobH123** [sile-typesetter/sile#832]
when installing SILE v0.10.3 from source on Ubuntu.

**Comment by RobH123** [comment]
FYI, apart from spending a bit of time solving this issue, rest of installation was straight forward and SILE is running now on forthcoming Ubuntu Focal (20.04) with Lua5.3.

**Comment by alerque** [comment]
@RobH123 This is actually mentioned in the instructions for installing [from source](https://github.com/sile-typesetter/sile#from-source) in the README:

> Note that openssl-devel will be required for one of the Lua modules to compile¹.
>
> ¹ <sub>OpenSSL development headers are required to build luasec, please make sure they are setup BEFORE trying to build SILE! If you use your system's Luarocks packages this will be done for you, otherwise make sure you can compile luasec. You can try just this step in isolation before building SILE using luarocks --tree=/tmp install luasec.</sub>

Since these instructions are generic rather than specific to a distro (these are the source instructions) the exact package names differ, in your case it is "libssl-dev" instead of "openssl-devel".

Unfortunately the manual is a bit behind (see #616, #795). Is that where you looked?

By the way there is a PPA setup, but I suppose we need to enable Focal support eh?

**Comment by RobH123** [comment]
> @RobH123 This is actually mentioned in the instructions for installing [from source](https://github.com/sile-typesetter/sile#from-source) in the README:
@alerque Oh, I never saw the README. I started by trying the PPA mentioned in the release notice, then went to the manual. And I don't recall any reference in the manual to the README.
> 
> > Note that openssl-devel will be required for one of the Lua modules to compile¹.
> > ¹ OpenSSL development headers are required to build luasec, please make sure they are setup BEFORE trying to build SILE! If you use your system's Luarocks packages this will be done for you, otherwise make sure you can compile luasec. You can try just this step in isolation before building SILE using luarocks --tree=/tmp install luasec.
So because I tried the make first, does this mean that I have a Lua module or something that I need to remove?
> 
> Since these instructions are generic rather than specific to a distro (these are the source instructions) the exact package names differ, in your case it is "libssl-dev" instead of "openssl-devel".
After stumbling around for a bit, Google eventually helped me out.
> 
> Unfortunately the manual is a bit behind (see #616, #795). Is that where you looked?
Sure. Yeah.
> 
> By the way there is a PPA setup, but I suppose we need to enable Focal support eh?
Yes, from memory the install from the PPA failed coz of libICU wanting 60 whereas I have 63.

**Comment by RobH123** [comment]
I'll add this here coz it might be related to my bleeding edge installation??? Trying to typeset a USX Bible book: 
```
SILE book1
This is SILE v0.10.3-dirty
/usr/bin/lua: error loading module 'justenoughlibtexpdf' from file '/usr/local/lib/sile/justenoughlibtexpdf.so':
	libtexpdf.so.0: cannot open shared object file: No such file or directory
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	/usr/local/share/sile/core/libtexpdf-output.lua:1: in main chunk
	[C]: in function 'require'
	/usr/local/share/sile/core/sile.lua:70: in function 'core/sile.init'
	/usr/local/bin/sile:44: in main chunk
	[C]: in ?
```
Let me know what other details you need if it's not something obvious to you.

**Comment by alerque** [comment]
@RobH123 First of all, the installation docs are egg on _my_ face. I'll work on getting those updated for various platforms. It's getting simpler on many platforms, but there are a lot more of them supported now!

Second, your new error is likely related to path issues in Lua 5.3 on Ubuntu, but I'm not exactly sure what. It might just be an incomplete installation of some kind too. However I'm surprised you say it's related to processing USX in specific, are you sure it doesn't happen _all the time_? That's the main PDF output library that's not being found!

**Comment by mnjames** [comment]
I ran across this problem once when updating libraries without re-building SILE (see https://groups.google.com/forum/#!searchin/sile-users/justenoughlibtexpdf|sort:date/sile-users/qnGtf1lUsQo/9HD9iqHWAwAJ)

Another time it happened--when working with usx files--because I was running SILE from the wrong base directory (see https://groups.google.com/forum/#!searchin/sile-users/justenoughlibtexpdf|sort:date/sile-users/qnGtf1lUsQo/9HD9iqHWAwAJ)
