### ISSUE TITLE
line spacing issue

### ISSUE THREAD

**Issue by vkvallinayagam** [sile-typesetter/sile#868]
I have simple XML input file. I also have a Lua file to process it.  The XML is simple format with section, title, para. What I find puzzling is, the third para of the first section, always has a large line spacing than the other para.

I use sile-0.10.4. The PDF generation command is:

    ./sile -I temple.lua ./examples/kazhugu_malai.xml

The temple.lua is in classes folder.

Attachments: [sile_test.zip](https://github.com/sile-typesetter/sile/files/4627438/sile_test.zip) file has temple.lua and the input file kazhugu_malai.xml.
The [kazhugu_malai.pdf](https://github.com/sile-typesetter/sile/files/4627444/kazhugu_malai.pdf) is the output pdf.

**Comment by simoncozens** [comment]
The issue seems to be the missing "par" at the end of the "para" command. Essentially what you are doing is this:

```
Kalugumalai is 21 km and 22 km from Kovilpatti and Sankarankovil respectively. Kalugumalai is located at  9.152962, 77.704386.\font[family="DejaVu Sans", size="16pt"]{\bigskip{}Mythology}

The temple is highly related to the epic Ramayana as it is said that Sambathi, who helped Lord Murugan kill the demon Surapadman, was the brother of Jatayu.
```
and the paragraph is taking its leading from the section title. Because XML format doesn't know when a paragraph ends, it never calls the `par` command automatically to end a paragraph, so you need to do it - uncomment the `-- SILE.call("par")` line in temple.lua and it seems to work.

**Comment by alerque** [comment]
First, a couple of unrelated comments...

* Obviously I can't speak for what your plans for it are, but right now the thing you are including isn't really a class, it's just an included script. You would need to `return temple` at the end of it.

  Once you do that, you have a place to hook in and run things other than registering commands that will happen at the start of your documents:

  ```lua
  temple.init = function (self)
    -- Your stuff here
    return plain.init(self)
  end

  return temple
  ```

  Optionally you could edit XML with `<sile class="temple">`. Then you won't need the `-I temple.lua` either.

* You're getting a line overflow because you have non-English words that it's having trouble hyphenating according to English rules. You might consider adding adding custom hyphenations for anything it can't break. For example in the init mentioned before you could add:

  ```lua
  SILE.call("hyphenator:add-exceptions", {}, {[[
    san-kar-an-ko-il
  ]]})
  ```

  This will fix the overflow in the first line. You might have to to similar things for other words that don't follow regular English syllable patterns. You can test if a word will possibly hyphenate or not by running plain `sile` on the command line and checking your word by entering `SILE.showHyphenationPoints("sankarankoil", "en")`.

* I noticed there is quite a bit of extraneous white-space in your XML. It isn't directly related to the issue you are reporting, but just so you know this will get you into trouble in other scenarios because it will trip the typesetter up into a mode you may not be expecting. Outputting a leading space at the start of a command might get you out of vertical mode into horizontal mode before your command has a chance to do the things you intended it to do.

Now on to your question!

The line spacing is not fixed as you assume. It's actually a very complex topic, but it adjusts depending on the font, what you have on the line, how the page break is going to play out, etc. The default line spacing is actually slightly flexible. The reasons why the default `tex` line height mechanism works the way it does are too much to get into here, but for your purposes I would suggest using one of the other line-height mechanisms entirely. There are quite a few available and one of them might work more like you expect. For example you might add this to the `init()` function you made above:

```lua
SILE.require("packages/linespacing")
SILE.settings.set("linespacing.method", "fit-glyph")
SILE.settings.set("linespacing.fit-glyph.extra-space", "0.6ex plus 0.2ex minus 0.1ex")
```

Here is the result of all those fixes above: [kazhugu_malai.pdf](https://github.com/sile-typesetter/sile/files/4628264/kazhugu_malai.pdf)

**Comment by alerque** [comment]
Ha ... also what @simoncozens said, which I missed!

**Comment by vkvallinayagam** [comment]
Hello Everyone,
  I deeply thank you folks for the time and attention, you all gave. I was about to raise the issue of line-overflow in first line at first para. ( at word, sankarankovil). But alerque found this issue and elaborated on the fix.
  I have been trying different ways of programmatic generation of pdf. I tried pslib, pdflib . Then I realised this comes under the field of typesetting software. I felt something like Tex will help.
  But I always found the syntax of Tex, it's library eco-system like context, latex etc very unapproachable. 
  I found SILE to address many of my needs. XML for content separation. No Tex like language (Not Mandatory). Lua for scripting. Also I read in manual, it can do page-layout software like processing (something like scribus). 
  I appreciate your efforts into it. More particularly the sustained efforts into it. Many open-source software start with a big enthusiasm and become an abandon-ware. 
  I am trying to learn this software by setting myself small typesetting tasks. I mostly learn from the samples in examples folder.
  It was not quite clear what is the role of having a class versus initial script. alerque threw some light into it. 
  After few weeks, I will write a documentation for my own aid. Presently, it is not clear to what are the commands - like "par".  Is there anywhere it is documented. How is it related to latex or tex. Is it a subset or something slightly different. Should I learn latex or tex documentation to know the commands. I knew the command "par" was related to para. But did not know the meaning of the command and how to use it. 
  I am absolutely a beginner when it comes to tex. But I have around 30 years exp in software industry which rich experience in linux, scripting etc. I can pickup if the pointers to documentation are given.
  Personally, I believe the value of good typesetting software in present world is equivalent of printing press 4 centuries before. I feel SILE combines the right ingredients to give the tex like typesetting power to many developers. 
  In case, if the info I am looking for is in the manual, please be patient to point it. I read the manual but not sequentially but could not find it.

Regards
Vallinayagam

**Comment by alerque** [comment]
The documentation does not cover the internals of how the typesetter works, especially not how to understand when it will be in what mode (collecting horizontal nodes, collecting vertical boxes, pushing the above back to another frame/page, etc.). Consequently knowing what to expect and what to bake into new commands that you expect to use block-wise or inline is not super clear. That's something we could improve on for sure.

No you shouldn't have to learn TeX's internals to use SILE — that's half the point! Some of the typesetting concepts do come across, but the internal architecture of TeX engines does not.

**Comment by alerque** [comment]
Even though I think your issue is solved I'll leave this issue open to track making sure we at least expand a little bit in the manual an when to use `SILE.call("par")` vs. `SILE.typesetter.leaveHmode()` vs. doing nothing when developing custom commands.

**Comment by Omikhleia** [comment]
Looking at it... For the record, in §9.4 (as of 0.14.9) is kinda explicit already:
> A related but higher level command,
\autodoc:command{\par}, is more frequently used when writing a document and embedded in
the content. The \autodoc:command{\par} command first calls
\code{SILE.typesetter:leaveHmode()}, then inserts a vertical skip according to
the \autodoc:setting{document.parskip} setting, then goes on to reset a number of
settings that are typically paragraph-related such as hanging indents.

But all that section is dense and this is easy to miss. Also it doesn't really address "doing nothing when developing custom commands."
