### ISSUE TITLE
Small issues in compiling the example file test.sil in ubuntu 20.04

### ISSUE THREAD

**Issue by hmslima** [sile-typesetter/sile#869]
*After solving the problem of installing SILE in \*ubuntu 20.04 (#852), I finally could compile a .sil file in my operating system, but I've faced two minor problems.*

In order to test SILE, I downloaded the file [test.sil](https://raw.githubusercontent.com/sile-typesetter/sile/master/examples/test.sil) to my folder `Downloads`.

<hr>

**1 -** I don't know if I did something wrong, but the [manual](https://sile-typesetter.org/manual/sile-0.10.4.pdf) says that I don't need to provide the file extension in the command line for compiling the file. But SILE was not able to find the file.

```
$ sile test
This is SILE v0.10.4

! Unable to find file test
        no file 'test' at       test


! Could not find file at        test
```

But it was not an actual problem since the command `sile test.sil` did the job, but would be good if you check this issue for \*ubuntu-based operating systems.

Here is the file compiled by me: [test.pdf](https://github.com/sile-typesetter/sile/files/4672260/test.pdf)
Here is the compiled file provided by your website: [test.pdf](https://raw.githubusercontent.com/sile-typesetter/sile/master/examples/test.pdf)

*I must say that I didn't make any modification in the original .sil file when I compiled it.*

<hr>

**2 -** The .sil document requires two font families: *DejaVu Sans* and *Snell Roundhand*.

**2.1 -** I've compared the texts of the file generated by me and the one made by you. The texts in the PDFs have visibly different fonts except the title, you can check it by yourselves. It's a lack of consistency, correct me if I am wrong, but theoretically I should get the very same result in any operating system, no matter if I am in Windows, \*ubuntu, macOS or Arch Linux, I am right?

**2.2 -** It's not a programming problem, but you should think about it. Your example .sil file requires the font *Snell Roundhand* that is not installed in my operating system and also seems that it's not even available in the \*ubuntu repositories.
I suppose that most of you are macOS users because this font indeed comes with the Apple's operating system, but it seems not be the case for Windows (even with Microsoft Office) and most Linux distributions.
```
$ sile test.sil
This is SILE v0.10.4
<test.sil>
[1] [2] [3] [4] [5] [6] [7] [8] [9] [10] [11] [12] [13] [14] [15] [16] [17] [18] [19] [20] [21] [22] [23] 
! Font family 'Snell Roundhand' not available, falling back to 'FreeMono' at in "␤My Dear Mr Sher…" near test.sil:533:1: in \fonttable: 0x557b17efb640
[24] [25] [26] 
```
I could manually download and install this font, but SILE used an alternative one in order to complete the compilation anyway. But wouldn't be better if you used only "safe fonts" for your example file instead?
I am glad that SILE doesn't push megabytes and megabytes of fonts to my hard drive like Latex does, but situations like this make me think if a very small set of fonts wouldn't be welcome...

**Comment by alerque** [comment]
Thanks for the issue report(s). In the future if we could request separate issues for each actual issue it would be a lot easier to track what things are resolved and what are open. Thanks ;-)

1. You didn't do anything wrong, the documentation in wrong. We started out with that auto-guessing 'feature', but it turned out to be quite problematic. As a simple example we can process `*.sil` or `*.xml` (or even `*.md` or `*.lua` or others ). One project may even use more than one at once. We simply can't resolve which one to use and it was causing too many problems trying to stab in the dark, so we removed it entirely. We updated a lot of the documentation, but we messed that line. My PR #870 should fix that, let us know if there are any more places we missed!

2. The test document really isn't meant to produce a pixel-perfect match when rendered, only to demonstrate that it does render text. This goes for most SILE documents: The documents themselves are not really meant to be "portable" on their own, the PDF output is what is meant to render the same for everyone. Given _all_ the inputs being the same it shouldn't matter what OS you are on. In fact we have a test suite of documents that are setup to match the exact renderings that we run on Arch Linux, Ubuntu, and macOS before committing anything to the project these days, but the **environment** is tightly controlled to get that effect. Notably you must provide exactly the same version of the font files to get the same output. In spite of having the name "test.sil" that file is not part of the test suite and you didn't build it with the test environment fonts. Even a small difference like one kerning adjustment in a font could potentially cause a whole document to render differently. Substituting a different font because your system didn't have one will produce a quite different document.

   We have tried to make SILE consistent so that **given the same input** it generates the same output consistently across platforms, but you have to provide the inputs—fonts being part of the input. We want SILE to do one job and to it well, it isn't meant to provide an end to end solution. It doesn't and won't bundle a lot of fonts or a clip-art library or whatever. (See #467)

   SILE has zero hard dependencies on fonts being installed on your system, and only one "soft" dependency on Gentium Plus as it's default font. You can still render documents without it, but that's its default requested font.

   There are no such things as "safe" fonts that are on all systems and platforms. That is a myth perpetrated by web designers that don't actually know what is under the hood. Even if a handful of family names are more widely available than others (e.g. Times New Roman), there are far more systems that you would thing that are just substituting similar fonts because of licensing issues. Even when they are the same font, they are often different versions.

   I'm all for making our examples use open-licensed fonts that people *can* get their hands on relatively easily –and I've been slowly working on that across the board, see issues like #854– but I don't think we should perpetrate the myth that there are "safe" fonts or make that our criteria for choosing fonts in examples.

   By the way you can substitute fonts using your system's *fontconfig* setup files to specify what fonts you want to substitute for others.

**Comment by hmslima** [comment]
Oh, I understand. Thank you for the clarification. I am loving this software.

**Comment by alerque** [comment]
See also #853.
