### ISSUE TITLE
Can we have dot leaders that are vertically aligned, please?

### ISSUE THREAD

**Issue by dajare** [sile-typesetter/sile#875]
I see there has been [some kerfuffle with dot leaders][i] recently, and that [a solution][s] (of sorts, at any rate) is on the way.

However, where dot leaders are used (typically, but not exclusively in tables of contents), then  one would expect all the leaders to align vertically, e.g.:

- [<img width="303" alt="__0-0a-sile-toc1" src="https://user-images.githubusercontent.com/40625/82942357-bd1aa080-9f8f-11ea-968f-4a1d0356a4ad.png">](https://archive.org/details/earlypoemsofwill00morr/page/n13/mode/2up)
- [<img width="289" alt="__0-0a-sile-toc2" src="https://user-images.githubusercontent.com/40625/82942362-c0159100-9f8f-11ea-9dae-323a5a22d9a6.png">](https://archive.org/details/manualoflinotype00merg/page/7/mode/1up)

Of course, there are innumerable examples, but this is so deeply engrained when dot leaders are used (of course, sometimes [they're not][t]) that to have any other layout arrangement would be odd. 

I would think a "typesetting engine" would want to make such vertically aligned dot leaders possible, at any rate. (Apparently, [it can be a challenge!][p])

[p]: http://www.ftp.tug.org/TUGboat/tb33-3/tb105veytsman-leaders.pdf
[t]: https://twitter.com/teropa/status/1028669612618141696
[i]: https://github.com/sile-typesetter/sile/issues/859
[s]: https://github.com/sile-typesetter/sile/pull/874

**Comment by cmahte** [comment]
This is probably a change in PA itself, but it is possible in indesign with
the tabstop definitions in the paragraph style for the table of contents.
(Think   of it as to right align the whole line and let the tabstop push
the content entry to the left.)

**Comment by Omikhleia** [comment]
Let's do some homework.

Ok, both our implementation of `dotfill` and `leaders` are likely wrong... Let's do some homework!

_First, the unitary "dot" element and its spacing_

Our implementation is currently using (1spc) "." (1spc), since #874. Before this, it was (inter-word variable space) "." (inter-word variable space). The switch to 1spc in #874 was no doubt better! But both are actually typographically wrong. Let's look at what old-time typographers used...
 - (French) "points conducteurs" in [Frey & Bouchez, 1857](https://books.google.fr/books?id=Tq_DT8yrnn4C&pg=PA307&redir_esc=y#v=onepage&q&f=false): formerly, it  used to be a dot inside a "cadratin" space (= 1em or quad, hence the huge spacing we see in fairly old books - I suspect this is the case for the two illustration in the initial issue description). At their time, it was however often within a demi-quadratin (= 1en or 0.5em) plus a dot, though other "regular (fixed) spaces" are not out of question. They discuss briefly where the space is often to be seen: on the right after the dot (which they criticized pretty negatively), evenly distributed (which they seem to recognized as the most common situation). They advocate (but the conditional wording seem to imply this is rarely the case in actual print) that it should be before the dot.
 - LaTeX sources: the space is evenly distributed around the dot, and is, by default, 4.5mu. Doh. Ok, let's dig deeper... Ah, a mu is a mathematical unit (don't ask me why it's used here), and 18mu = 1em (_please_, don't ask me why). So... Erm, 4.5mu = 0.5en (0.25em), and overall this is in line with the above standard definition. But this is a _default_ value, `\@dotsep=4.5`.

*Conclusion*: I'd suggest a setting (call that `leader.dotsep` ?) with default value 0.25em, and we use that as a kern instead of the current 1spc. This leaves the option for users to change its value, would they want more spacing, for their book to look "old-style".

_Then, the leaders alignment logic_

I could go on with details, but after all the [CSS discussion](https://www.w3.org/TR/css-gcpm-3/#procedure-leader) is not that bad (see especially figure 7). How could it be used in our case?

I'll focus on the general case (more than 1 repetition). Currently we compute a remainder and distribute it evenly around our dots line. This is obviously wrong:
- Leaders are ideally computed from the "end position". So the right if we are in LTR, or the left in RTL. We might consider this refers to the current frame (as a wild guess, but I am right to assume that it would that be general enough?)
- We can know where out leader box will end, and compute the offset for the first dot relatively to the end position (i.e. how many dots are "cancelled" by the content between the frame/line end position and own position)
- We can proceed backward to where and just stop when we reach beyond the leader box starts.

I might give that a try, but I am beyond schedule on my own projects - so if someone wants to try before, go ahead, and I'll be more than happy to review. Don't forget the tests and proper documentation...

**Comment by Omikhleia** [comment]
I wonder if I correctly interpret my own prose above and this "quick prrof of concept" would be the valid disposition?
![image](https://user-images.githubusercontent.com/18075640/159340353-1b64e41d-b366-4833-a612-e9c910c03b3e.png)

**Comment by Omikhleia** [comment]
No, we can simplify (à la LaTeX) without the tricky overlaps and this is still looking kinda correct.

![image](https://user-images.githubusercontent.com/18075640/159376571-15cbdd1e-2ef9-41cb-98b8-1f333f80f74f.png)

I'll make that into a PR.
