### ISSUE TITLE
can't run on windows 10

### ISSUE THREAD

**Issue by simsoueu** [sile-typesetter/sile#887]
Hi, I've been interested in trying out sile, read a coulple of articles and the manual.

However I could not install properly on windows. First I downloaded the source but don't feel like installing cmake and Visual Studio right now it would take too long.

Then I the second method advised here on github, tried using the pipeline but I get the error './core/sile.lua:3: module 'compat53' not found.

Okay I know that if you tried a little harder I think I would be able to install lua to finnaly trying out sile. 

But do you realise how much effort is required to just try and see if I like or not this typesetter. I know that your target audience are proggrammers and many of them are linux/mac users and thats fine, however windows still a huge platform I if you want to make this project successful the installation on windows, should be a higher priority for sure.

Anyways I know that this sound like I am an entited person, but I say this as someone who has been using LaTeX for about 4 years and I desperetly wanted somethig better, simpler and faster.

Observation: Other  that focus on installation on windows I would suggest too to make support for math a little better, from the manual I undesrtood that it wasn't a priority.

**Comment by alerque** [comment]
Yes, we know this is an issue: @simoncozens works from macOS and I work from Linux. Given that we both are primarily driven to develop SILE for our own uses, it's kind of hard to justify a bunch of time and effort to setup a Windows box, learn the ins and outs of development there, and make this happen. It's in large part thanks to @harrysummer that there is any Windows support at all. That being said I think we're both aware that easy to setup Windows packaging would be a great thing for a lot of people and overall benefit the project through the influx of users.

Still, somebody has to be motivated to make it happen. Care to volunteer? 

Briefly in the case of the specific error you mention, the `compat53` module should not be needed for Lua 5.3 at all. It sounds like the solution would either be switch to Lua 5.3 or –in the event it already is 5.3– fix the Lua version detection on Windows so that it knows it doesn't need that module. I'm guessing the `CMakeLists.txt` needs to be taught that that module is a special case needed for older Luas.

**Comment by alerque** [comment]
See also #410.

**Comment by hmslima** [comment]
That's sad. I just switched from Linux to Windows and seems that I will not be able to test SILE for a long time.

**Comment by mnjames** [comment]
> 
> 
> That's sad. I just switched from Linux to Windows and seems that I will not be able to test SILE for a long time.

I've been running SILE for a few years under the Windows Subsystem for Linux and have been very happy with it. It's not quite as easy to set up as a standard Windows install might be, but for someone who's used Linux it shouldn't be too difficult. I prefer WSL over a virtual machine because it boots up quicker and (with WSL2) should be faster.

**Comment by alerque** [comment]
I'm not trying to downplay this, we really would like to see a native Windows install that's easy to get off the ground with. In the mean time Windows isn't completely stranded.

1. There _are_ Windows builds that run. We can track down the links but we did have some versions that ran. The bug reported above in package deps is likely a new thing. Meanwhile Windows builds are currently still happening. They don't generate an installer yet but they do generate builds.
1. You can also run it using Docker.
1. You can run it under WSL.
1. You can run it under NIX.

**Comment by Omikhleia** [comment]
Duplicates #410
