### ISSUE TITLE
Document can't end with a \font[family=EB Garamond] ... if Inconsolata was used.

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#934]
MWE:

```tex
\begin{document}
Fredrick R Brennan
\font[family=Inconsolata]
copypastekittensph
\font[family=EB Garamond]
% o % uncommenting me fixes everything
\end{document}
```

```
libtexpdf:fatal: Invalid GID.
```

Could be related to #932?

This one is bizarre. If family is not EB Garamond at the end there, SILE exits as normal.

**Comment by alerque** [comment]
About two hours ago I ran into something similar while working on new fonts for documentation (#854) here it crashed at the very end of the document. I'm out and about but will look into this when I get back. Definitely a strange one.

**Comment by alerque** [comment]
I tracked down the problem from my previous comment, and it was unrelated to this (bad file permissions on a TOC file).

I am completely unable to replicate this issue. I'm not saying it doesn't exist, just that there doesn't seem to be enough information here to put it back together and replicate the crash.

One thing that _could_ be involved is a corrupt font. Adding `-d versions` to a SILE run on your MWE so we can see what font files I'm running shows something like this (with the last line enabled so EB Garamond actually gets used):

```
$ ./sile -d versions t.sil
This is SILE v0.10.5.r107-g36868e2
<t.sil>
[1]
Harfbuzz version: 2.6.8
Shapers enabled: graphite2, ot, fallback
ICU support enabled

Fonts used:
/usr/share/fonts/OTF/EBGaramond08-Regular.otf:0 Version 0.016
/usr/share/fonts/TTF/Inconsolata-Regular.ttf:0  Version 3.000; ttfautohint (v1.8.3)
/usr/share/fonts/gentium/GentiumPlus-R.ttf:0    Version 5.000
```

Note with the last line commented out as in your attempted MWE, I don't even get a version dump here because it never actually even _tried_ to use EB Garamond for anything.

The test above is run using the latest HEAD commit on the *master* branch, but I get the same results with the release of v0.10.5.

Perhaps have a look at what font files you are using, zip up those exact files and attach them here and I'll check if I get the same results using your font files?

Also please add the output of a stack trace on the problem by adding `-t` to your invocation. Debugging the fonts system might be revealing too, so `sile -t -d fonts,versions mwe.sil` or something like that.

**Comment by ctrlcctrlv** [comment]
Closing for now, I can't seem to figure out how I caused this either. If it happens again I'll take more careful note of the fonts I was using.
