### ISSUE TITLE
How should I escape characters in command parameters ( [] )?

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#937]
MWE:

```tex
\fbox[width=1zw,_=\]\,sup]{hi}
```

If I set fbox to...
```
function(o,c)
  SU.dump(o)
  print()
  SU.dump(c)
end
```

```lua
This is SILE v0.10.5
<tkana.sil>
{
  _ = "\\",
  width = "1zw"
}
{
  col = 1,
  command = "fbox",
  id = "texlike_command",
  lno = 59,
  options = {
    _ = "\\",
    width = "1zw"
  },
  pos = 3382
}
```

**Comment by simoncozens** [comment]
Put them in double quotes?

**Comment by ctrlcctrlv** [comment]
```tex
\fbox[width=1zw,_="],sup\""]{hi}
```

**Comment by alerque** [comment]
Quoting them should have worked. In fact it does for all those cases (`]`, `,`, ` `, etc.) except for the double quote more. There is currently no provision for escaping a quote mark in an argument. This is a deficiency in the PEG grammar and I'm working on fixing it.

**Comment by alerque** [comment]
For starters, I think we we a little too generous allowing characters as part of command names. I don't think we _meant_ for this to work (but it does):

```
\begin{document}
\script{SILE.registerCommand("\"", function (o, c)
  SU.dump(o, c)
end)}
\"
\end{document}
```

**Comment by alerque** [comment]
We have strict rules about what characters can define commands (ASCII letters & Arabic numerals for starting, thereafter any of those plus colons or dashes. Then starting with f1ef2a20 we throw all that out the window and allow *any* character for single letter commands. That creates all sorts of side effects. I think the right solution is to stick to the same rules for allowed characters plus to whitelist the specific characters we need to dodge the bits we use in the language, namely `{`, `}`, `\`, and `%`. We document that those are the only things that need escaping, so I think they are the only exceptions we should make for what letters are allowed in commands. Otherwise we run into weird edge cases such as we let people define `\"` as a command but not `\a"`, and `\-` but not `\-a` and so on.

Also more relevant to *this* issue it makes using escape sequences crazy hard which it should be pretty easy. In this case we only need one escape sequence: the one that would otherwise terminate the grammar.
