### ISSUE TITLE
It is kind of annoying that when you update SILE from source Luarocks complains modules already exist

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#976]
```
Error: Failed installing dependency: https://luarocks.org/luasec-0.9-1.src.rock - File already exists: /home/osboxes/Workspace/sile/lua_modules/share/lua/5.2/luasec_0_8_1_1-ssl.lua
```

Fixed by `mv lua_modules lua_modules.bak && make install`

**Comment by alerque** [comment]
I've never seen this, and I've done thousands of iterations of various builds. What sequence of commands landed you at this error? Is the directory you are moving out of the way one installed on your system ("/usr/share/...") or the one in the source directory?

**Comment by ctrlcctrlv** [comment]
It's a build from a Git clone on Xubuntu 20.04 which also has the PPA SILE as system SILE.

So on one day I `git clone`'d, `./bootstrap`'d, `make install`'d.

Then I `git pull`'d, `./bootstrap`'d again as `make install` didn't work, and `make install` and got error.

It's complaining about the `lua_modules` in the build directory.

**Comment by ctrlcctrlv** [comment]
Oh, I should note, both times I also did `./configure --prefix=/opt`

**Comment by alerque** [comment]
Okay, I'll try to replicate this. I do something quite similar frequently though and I don't see what's different.

Just a note though that you shouldn't need to (and probably shouldn't) re-run the `./bootstrap.sh` script after a `git pull`, nor do you even need to re-run `./configure`. It will keep your configuration and re-run the parts of it that need to refresh when the Git HEAD changes. The only time you need to bootstrap is when you do a fresh clone (or blow away the stuff it sets up with `git clean -dxff` or something like that).

**Comment by alerque** [comment]
I can't replicate this. My attempt looks like this (on a system that has an Arch system that also hase a `/usr` prefixed installation from system packages):

1. Fresh clone, then `git checkout v0.10.5` (you didn't specify what commit you were coming from, so I just picked something older than the problematic 6/7/8 releases that have cross platform make issues)
1. `./bootstrap.sh && ./configure --prefix /opt`
1. `make install DESTDIR=/tmp/issue796`
1. `git checkout master`
1. `./bootstrap.sh && ./configure --prefix /opt` (needed in spite of my previous note because what `./bootstrap.sh` does changed in the last release, also because it's what you said you did)
1. `make install DESTDIR=/tmp/issue796`

No error

1. Checkout to the branch for #969 which has an overhaul of how lua_modules is handled
1. `make install DESTDIR=/tmp/issue796`

Still no error.

**Comment by ctrlcctrlv** [comment]
I don't know why this would change anything, but my HEAD was at #940's commit, not 0.10.5, then `git pull` brought me to 175baad18d6f2b1591d2d941c346e7f7ba8b293c

If you say this has never happened to you, I'm happy to close this and chalk it up to a glitch in the matrix :-)

**Comment by alerque** [comment]
There is at least one glitch still poking through the matrix which is why my efforts on #969 have a bunch of "foo" commits on the end, why v0.10.9 isn't a thing, and why I'm loosing hair. I can't think it would have any effect on this though.

By the way what version is your system's Lua & LuaRocks?

**Comment by ctrlcctrlv** [comment]
```
osboxes@osboxes:~/Workspace/sile$ luarocks --version
/usr/bin/luarocks 2.4.2
LuaRocks main command-line interface

osboxes@osboxes:~/Workspace/sile$ lua -v
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
```

**Comment by alerque** [comment]
I'm still as baffled as I was at first, but that error at the start of this thread is a LuaRocks generated error. I'm happy to fix this if there is a problem on our end, but I suspect this is at least partially LuaRocks fault. That's a particularly old version (current is 3.3.1) and lots of known issues have been fixed. That being said I've also tested this on Ubuntu Bionic which comes with 2.4.2 and haven't been able to replicate this.

In addition to that, between v0.10.8‌ and v0.10.9 (which is building as we speak) there have been significant changes to how we handle Lua dependencies. Versions of rocks for all possible supported Lua versions are no longer bundled in source tarballs, and because it isn't juggling that mess building from Git is a lot cleaner too.

In addition to the Lua handling being changed, the Makefile has a lot of changes to how it determines build order making it a lot saner to skip straight from `./configure` to `make install` than it was before, and also not cause as many unnecessary rebuilds when doing development work.

Between all these factors I‌think I'm going to close this issue and hope it goes away. I'm really crossing my fingers whatever caused this has been dealt with via the above.

If not and this crops up ever again please *don't* spare my feelings and *do* re-open this issue with whatever new information you have and I'll re-evaluate.
